"""Shadow and canary rollout for a generated skill (ACCEPTANCE_TESTS M7
lifecycle; EVOLUTION_ENGINE_SPEC §4 "Sandbox/shadow/canary -> metric comparison").

Both stages run the SAME deterministic case set through the candidate and,
when one exists, through the currently registered incumbent — each in its own
isolated subprocess, using the same isolation as evaluation (``-I -S``,
allowlist-built environment, no production secrets).

- **Shadow** mirrors traffic: the candidate is executed but its answers are only
  compared, never served. Evidence: samples, mismatches, errors.
- **Canary** serves a bounded sample and compares the candidate's success rate
  and p95 latency against the incumbent's. Evidence:
  ``not_worse_than_incumbent``, both scorecards.

A brand-new capability has no incumbent; the comparison then falls back to the
declared expectations (the candidate must be perfect on its own eval set), which
is exactly the "no incumbent to be worse than" case.
"""

from __future__ import annotations

import json
import tempfile
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

from app.evolution.errors import EvolutionError, EvolutionErrorClass
from app.evolution.evaluation import SkillEvaluator, run_skill_script
from app.evolution.skills import SKILL_DIR_ENV, SkillLayout
from app.logging import get_logger

logger = get_logger("app.evolution.rollout")

CASES_ENV = "PAGENTOS_ROLLOUT_CASES"

# A stdlib-only driver: loads the skill under test and replays the case file.
_DRIVER_SOURCE = f'''"""Rollout driver (generated by the Evolution Engine). Stdlib only, offline."""

import importlib.util
import json
import os
import sys
import time

skill_dir = os.environ[{SKILL_DIR_ENV!r}]
with open(os.environ[{CASES_ENV!r}], encoding="utf-8") as handle:
    payload = json.load(handle)

spec = importlib.util.spec_from_file_location(
    "skill_under_rollout", os.path.join(skill_dir, "src", payload["module"] + ".py")
)
module = importlib.util.module_from_spec(spec)
spec.loader.exec_module(module)

results = []

if payload.get("mode") == "payload":
    # M24 (ADR-0087): a genesis HTTP adapter's run(payload) takes/returns a
    # dict of arbitrary shape (zero, one or many fields) rather than the single
    # scalar input_name/output_name shape pure-transform skills use, and its
    # result is state-dependent (a live application), so a case
    # asserts SHAPE conformance (declared field names + types) rather than an
    # exact value — the same thing evaluated once here, once in the eval set.
    def _shape_ok(value, kind):
        if kind == "integer":
            return isinstance(value, int) and not isinstance(value, bool)
        if kind == "number":
            return isinstance(value, (int, float)) and not isinstance(value, bool)
        if kind == "boolean":
            return isinstance(value, bool)
        if kind == "string":
            return isinstance(value, str)
        return False

    for case in payload["cases"]:
        started = time.perf_counter()
        try:
            actual = module.run(dict(case.get("input") or {{}}))
            shape = case.get("expected_shape") or {{}}
            required = case.get("expected_required") or list(shape)
            ok = isinstance(actual, dict) and all(
                name in actual and _shape_ok(actual[name], shape[name]) for name in required
            )
            error = "" if ok else "shape_mismatch"
        except Exception as exc:  # noqa: BLE001 - rollout harness
            actual = None
            ok = False
            error = type(exc).__name__
        results.append(
            {{
                "actual": actual,
                "expected": None,
                "ok": ok,
                "error": error,
                "latency_ms": (time.perf_counter() - started) * 1000.0,
            }}
        )
else:
    input_name = payload["input_name"]
    output_name = payload["output_name"]
    for case in payload["cases"]:
        started = time.perf_counter()
        try:
            actual = module.run({{input_name: case["input"]}})[output_name]
            error = ""
        except Exception as exc:  # noqa: BLE001 - rollout harness
            actual = None
            error = type(exc).__name__
        results.append(
            {{
                "actual": actual,
                "expected": case.get("expected"),
                "ok": (error == "" and actual == case.get("expected")),
                "error": error,
                "latency_ms": (time.perf_counter() - started) * 1000.0,
            }}
        )

total = len(results)
passed = sum(1 for r in results if r["ok"])
latencies = sorted(r["latency_ms"] for r in results)
p95 = latencies[min(len(latencies) - 1, int(len(latencies) * 0.95))] if latencies else 0.0
print(
    "ROLLOUT-RESULT "
    + json.dumps(
        {{
            "samples": total,
            "passed": passed,
            "failed": total - passed,
            "errors": sum(1 for r in results if r["error"]),
            "success_rate": (passed / total) if total else 0.0,
            "p95_latency_ms": p95,
            "results": results[:50],
        }},
        ensure_ascii=False,
    )
)
sys.exit(0)
'''

ROLLOUT_PREFIX = "ROLLOUT-RESULT "


@dataclass(slots=True)
class RolloutScore:
    samples: int = 0
    passed: int = 0
    failed: int = 0
    errors: int = 0
    success_rate: float = 0.0
    p95_latency_ms: float = 0.0

    def to_dict(self) -> dict[str, Any]:
        return {
            "samples": self.samples,
            "passed": self.passed,
            "failed": self.failed,
            "errors": self.errors,
            "success_rate": round(self.success_rate, 6),
            "p95_latency_ms": round(self.p95_latency_ms, 6),
        }


@dataclass(slots=True)
class RolloutReport:
    stage: str
    candidate: RolloutScore
    incumbent: RolloutScore | None = None
    not_worse_than_incumbent: bool = True
    mismatches: int = 0
    detail: dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> dict[str, Any]:
        return {
            "stage": self.stage,
            "samples": self.candidate.samples,
            "mismatches": self.mismatches,
            "not_worse_than_incumbent": self.not_worse_than_incumbent,
            "candidate": self.candidate.to_dict(),
            "incumbent": self.incumbent.to_dict() if self.incumbent else None,
            "detail": dict(self.detail),
        }


def load_eval_cases(layout: SkillLayout) -> dict[str, Any]:
    """The case set the rollout replays, taken from the generated eval set.

    Two shapes: the original single-scalar ``{input_name, output_name, cases:
    [{input, expected}]}`` (every pure-transform skill), and the M24 "payload"
    shape a genesis HTTP adapter emits (``mode: "payload"``, each case's
    ``input``/``expected_shape`` a dict) — see ``rollout.py``'s driver source.
    """
    if not layout.cases_path.is_file():
        raise EvolutionError(
            EvolutionErrorClass.NOT_FOUND, "generated eval cases are missing; cannot roll out"
        )
    payload = json.loads(layout.cases_path.read_text(encoding="utf-8"))
    result: dict[str, Any] = {"module": layout.skill_name, "cases": payload["cases"]}
    if payload.get("mode") == "payload":
        result["mode"] = "payload"
    else:
        result["input_name"] = payload["input_name"]
        result["output_name"] = payload["output_name"]
    return result


def run_cases(
    layout: SkillLayout,
    payload: dict[str, Any],
    *,
    evaluator: SkillEvaluator | None = None,
) -> RolloutScore:
    """Replay a case set against one skill directory, in isolation."""
    evaluator = evaluator or SkillEvaluator()
    work = Path(tempfile.mkdtemp(prefix="evolution-rollout-"))
    try:
        driver = work / "driver.py"
        driver.write_text(_DRIVER_SOURCE, encoding="utf-8")
        cases_file = work / "cases.json"
        cases_file.write_text(
            json.dumps({**payload, "module": layout.skill_name}, ensure_ascii=False),
            encoding="utf-8",
        )
        run = run_skill_script(
            driver,
            layout.root,
            python=evaluator.python,
            timeout_s=evaluator.timeout_s,
            extra_env={CASES_ENV: str(cases_file)},
        )
        if run.timed_out:
            raise EvolutionError(
                EvolutionErrorClass.RESOURCE_BUDGET_EXCEEDED,
                "rollout run exceeded the configured execution timeout",
            )
        for line in run.stdout.splitlines():
            if line.startswith(ROLLOUT_PREFIX):
                data = json.loads(line[len(ROLLOUT_PREFIX) :])
                return RolloutScore(
                    samples=int(data["samples"]),
                    passed=int(data["passed"]),
                    failed=int(data["failed"]),
                    errors=int(data["errors"]),
                    success_rate=float(data["success_rate"]),
                    p95_latency_ms=float(data["p95_latency_ms"]),
                )
        raise EvolutionError(
            EvolutionErrorClass.EVALUATION_FAILED,
            "rollout driver produced no result",
            details={"stderr_tail": run.stderr[-500:]},
        )
    finally:
        import shutil

        shutil.rmtree(work, ignore_errors=True)


class ShadowRunner:
    """Mirrors the case set through the candidate; nothing is served."""

    stage = "shadow"

    def __init__(self, evaluator: SkillEvaluator | None = None) -> None:
        self.evaluator = evaluator or SkillEvaluator()

    def run(
        self, candidate: SkillLayout, incumbent: SkillLayout | None = None
    ) -> RolloutReport:
        payload = load_eval_cases(candidate)
        candidate_score = run_cases(candidate, payload, evaluator=self.evaluator)
        incumbent_score = (
            run_cases(incumbent, payload, evaluator=self.evaluator) if incumbent else None
        )
        report = RolloutReport(
            stage=self.stage,
            candidate=candidate_score,
            incumbent=incumbent_score,
            mismatches=candidate_score.failed + candidate_score.errors,
            not_worse_than_incumbent=(
                incumbent_score is None
                or candidate_score.success_rate >= incumbent_score.success_rate
            ),
            detail={"traffic": "mirrored", "served": False},
        )
        logger.info(
            "shadow_completed",
            capability_id=candidate.capability_id,
            samples=candidate_score.samples,
            mismatches=report.mismatches,
        )
        return report


class CanaryRunner:
    """Serves a bounded sample and compares against the incumbent."""

    stage = "canary"

    def __init__(
        self, evaluator: SkillEvaluator | None = None, *, sample_size: int = 5
    ) -> None:
        self.evaluator = evaluator or SkillEvaluator()
        self.sample_size = sample_size

    def run(
        self, candidate: SkillLayout, incumbent: SkillLayout | None = None
    ) -> RolloutReport:
        payload = load_eval_cases(candidate)
        payload = {**payload, "cases": payload["cases"][: self.sample_size]}
        candidate_score = run_cases(candidate, payload, evaluator=self.evaluator)
        incumbent_score = (
            run_cases(incumbent, payload, evaluator=self.evaluator) if incumbent else None
        )
        if incumbent_score is None:
            not_worse = candidate_score.success_rate >= 1.0
            reason = "no incumbent; candidate must be perfect on its own case set"
        else:
            not_worse = candidate_score.success_rate >= incumbent_score.success_rate
            reason = (
                f"candidate {candidate_score.success_rate:.3f} vs incumbent "
                f"{incumbent_score.success_rate:.3f}"
            )
        report = RolloutReport(
            stage=self.stage,
            candidate=candidate_score,
            incumbent=incumbent_score,
            mismatches=candidate_score.failed + candidate_score.errors,
            not_worse_than_incumbent=not_worse,
            detail={"traffic": "bounded_sample", "sample_size": self.sample_size,
                    "comparison": reason},
        )
        logger.info(
            "canary_completed",
            capability_id=candidate.capability_id,
            samples=candidate_score.samples,
            not_worse=not_worse,
        )
        return report


__all__ = [
    "CASES_ENV",
    "ROLLOUT_PREFIX",
    "CanaryRunner",
    "RolloutReport",
    "RolloutScore",
    "ShadowRunner",
    "load_eval_cases",
    "run_cases",
]
