"""Bozuk Türkçe kapıda: recognise Turkish text that was read with the wrong encoding.

A BOM-less ``.ps1`` under Windows PowerShell 5.1 reads its UTF-8 source as cp1252, so "Yöneticisi"
reaches the api as "YÃ¶neticisi". :func:`find_mojibake` looks for the two- and three-character
PAIRS such a reading produces (:data:`MOJIBAKE_PAIRS`), never for a single letter: "São Paulo" or
"Ãlvaro" are real names. :func:`scan_payload` walks a request body for the first such pair and
:func:`mojibake_detail` builds the 422 detail - naming the pair and the correct letter only, never
the rejected text (KVKK: it is neither echoed nor logged).

Pure: no I/O, no import of the team store, routes or board. The write endpoints call it before
any store write (see team/plans/mojibake-write-rule-adr.md).
"""

from __future__ import annotations

import re
from dataclasses import dataclass

# The cp1252 reading of each letter's UTF-8 bytes -> the letter. Generated by hand from
# ``letter.encode("utf-8").decode("cp1252")``; the unit test regenerates every entry.
MOJIBAKE_PAIRS: dict[str, str] = {
    "Ã¶": "ö",
    "Ã¼": "ü",
    "Ã§": "ç",
    "Ã–": "Ö",
    "Ãœ": "Ü",
    "Ã‡": "Ç",
    "Ä±": "ı",
    "Ä°": "İ",
    "ÄŸ": "ğ",
    "Äž": "Ğ",
    "ÅŸ": "ş",
    "Åž": "Ş",
    "â€”": "—",
    "â€“": "–",
    "â€œ": "“",
    "â€™": "’",
}

# Longest first, so a three-character pair is never shadowed by a shorter one.
_PATTERN = re.compile("|".join(re.escape(p) for p in sorted(MOJIBAKE_PAIRS, key=len, reverse=True)))

# Deeper than this a request body is not a real write: its deeper parts are not scanned.
MAX_DEPTH = 64


@dataclass(frozen=True)
class MojibakeHit:
    pair: str
    correct: str
    offset: int


def find_mojibake(text: str) -> MojibakeHit | None:
    """The earliest mojibake pair in ``text``, or None."""
    match = _PATTERN.search(text)
    if match is None:
        return None
    pair = match.group(0)
    return MojibakeHit(pair=pair, correct=MOJIBAKE_PAIRS[pair], offset=match.start())


def _join(parent: str, part: str) -> str:
    return f"{parent}.{part}" if parent else part


def scan_payload(value: object) -> tuple[str, MojibakeHit] | None:
    """The first mojibake in a str / dict / list / tuple, with its dotted path ('sections.0.text').

    A hit in a dict KEY is reported as ``<parent>.[anahtar N]`` (the key's position), so the key's
    own text is not echoed. Non-strings are ignored; cycles and nesting beyond :data:`MAX_DEPTH`
    are skipped (iterative, so never a RecursionError)."""
    seen: set[int] = set()
    stack: list[tuple[object, str, int]] = [(value, "", 0)]
    while stack:
        item, path, depth = stack.pop()
        if isinstance(item, str):
            hit = find_mojibake(item)
            if hit is not None:
                return path, hit
            continue
        if not isinstance(item, dict | list | tuple) or depth >= MAX_DEPTH or id(item) in seen:
            continue
        seen.add(id(item))
        children: list[tuple[object, str, int]] = []
        if isinstance(item, dict):
            for n, (key, child) in enumerate(item.items()):
                if isinstance(key, str):
                    children.append((key, _join(path, f"[anahtar {n}]"), depth + 1))
                children.append((child, _join(path, str(key)), depth + 1))
        else:
            children = [(child, _join(path, str(i)), depth + 1) for i, child in enumerate(item)]
        stack.extend(reversed(children))
    return None


def mojibake_detail(path: str, hit: MojibakeHit) -> dict[str, str]:
    """The 422 detail: the field, the pair and the correct letter - never the surrounding text."""
    return {
        "code": "mojibake",
        "field": path,
        "pair": hit.pair,
        "correct": hit.correct,
        "reason": (
            f"metin bozuk kodlanmış görünüyor: '{hit.pair}' → '{hit.correct}' olmalı; "
            "betiği BOM'lu kaydet"
        ),
    }
