<#
.SYNOPSIS
    Broker-registration restoration under actual Windows PowerShell 5.1, with a REAL
    enrolled ECDSA device key — the exact path a real finalize run died on.

.DESCRIPTION
    The failure this guards: finalize-qualification.ps1 called ECDsa.ImportFromPem from the
    5.1 host, whose .NET Framework does not have it. The fix routes all key handling through
    the agent's own .NET 10 implementation via `PagentOS.DeviceService identity`.

    Nothing here is mocked at the crypto or process level:

      * the REAL service executable performs a REAL enrollment (P-256 keypair generated by
        DeviceIdentity, state.json written by AgentState) against a loopback TCP listener
        this test operates — raw sockets, no HttpListener URL-ACL requirements, no
        elevation. The listener CAPTURES the public key the device registered with.
      * the same executable then answers `identity`, and the test asserts the returned
        public_key_spki_b64 is byte-for-byte the enrolled one. That equality IS the
        restoration property: restore_device_registration.py re-creates the broker row from
        exactly this value.
      * load-only is proven by refusal: `identity` against an empty data dir must exit 3
        and create nothing — the verb answering a recovery question must never mint one.

    Run: powershell -NoProfile -File scripts\tests\identity-restore.tests.ps1
    Exit code is the number of failed assertions.
#>

[CmdletBinding()]
param()

$ErrorActionPreference = "Stop"
Set-StrictMode -Version Latest

$repoRoot = Split-Path -Parent (Split-Path -Parent $PSScriptRoot)
. (Join-Path $repoRoot "scripts\lib\NativeProcess.ps1")

$script:Failures = 0
$script:Passes = 0
$script:Sandbox = Join-Path $env:TEMP "pagentos-identity-tests-$([guid]::NewGuid().ToString('N'))"

function Test-Case {
    param([string]$Name, [scriptblock]$Body)
    try {
        & $Body
        $script:Passes++
        Write-Host "  PASS  $Name"
    }
    catch {
        $script:Failures++
        Write-Host "  FAIL  $Name" -ForegroundColor Red
        Write-Host "        $($_.Exception.Message)" -ForegroundColor Red
    }
}

function Assert-True {
    param([bool]$Condition, [string]$Because)
    if (-not $Condition) { throw $Because }
}

function Assert-Equal {
    param($Expected, $Actual, [string]$Because)
    if ($Expected -cne $Actual) { throw "$Because`n          expected: <$Expected>`n          actual  : <$Actual>" }
}

function Get-HelperExe {
    <#  The real service executable, built if the bin output is absent.  #>
    $exe = Join-Path $repoRoot "devices\windows-agent\src\PagentOS.DeviceService\bin\Debug\net10.0-windows\PagentOS.DeviceService.exe"
    if (-not (Test-Path -LiteralPath $exe)) {
        $dotnet = Join-Path $env:LOCALAPPDATA "Microsoft\dotnet\dotnet.exe"
        if (-not (Test-Path $dotnet)) { $dotnet = (Get-Command dotnet -ErrorAction Stop).Source }
        $project = Join-Path $repoRoot "devices\windows-agent\src\PagentOS.DeviceService\PagentOS.DeviceService.csproj"
        $build = Invoke-NativeProcess -FilePath $dotnet -Arguments @("build", $project, "--nologo", "-v", "q") -TimeoutSeconds 600
        Assert-NativeSuccess -Result $build -Activity "build the device service for the identity tests"
    }
    if (-not (Test-Path -LiteralPath $exe)) { throw "service executable not found at $exe even after build" }
    return $exe
}

function Invoke-Helper {
    <#
    .SYNOPSIS
        Run the service exe with the agent environment pointing at a test data dir.
        Developer material posture, because in this test the runner IS the owner and the
        service account at once — exactly the posture that flag exists for.
    #>
    param([string]$Exe, [string]$DataDir, [string[]]$Arguments, [int]$TimeoutSeconds = 60)

    $psi = New-Object System.Diagnostics.ProcessStartInfo
    $psi.FileName = $Exe
    $psi.Arguments = ConvertTo-NativeArgumentLine -Arguments $Arguments
    $psi.UseShellExecute = $false
    $psi.RedirectStandardOutput = $true
    $psi.RedirectStandardError = $true
    $psi.CreateNoWindow = $true
    $psi.EnvironmentVariables["PAGENTOS_AGENT_DataDir"] = $DataDir
    $psi.EnvironmentVariables["PAGENTOS_AGENT_MachineMaterialMode"] = "developer"

    $process = [System.Diagnostics.Process]::Start($psi)
    $stdOutTask = $process.StandardOutput.ReadToEndAsync()
    $stdErrTask = $process.StandardError.ReadToEndAsync()
    if (-not $process.WaitForExit($TimeoutSeconds * 1000)) {
        try { $process.Kill() } catch { }
        throw "helper did not exit within ${TimeoutSeconds}s"
    }
    $process.WaitForExit()   # flush async readers
    return [pscustomobject]@{
        ExitCode = $process.ExitCode
        StdOut   = $stdOutTask.Result
        StdErr   = $stdErrTask.Result
    }
}

function Receive-EnrollmentPost {
    <#
    .SYNOPSIS
        Accept ONE HTTP POST on a raw loopback socket, return its parsed JSON body, and
        answer 200 with the given JSON. Raw TcpListener: no URL ACLs, no elevation.
    #>
    param([System.Net.Sockets.TcpListener]$Listener, [string]$ResponseJson, [int]$TimeoutSeconds = 30)

    $acceptTask = $Listener.AcceptTcpClientAsync()
    if (-not $acceptTask.Wait($TimeoutSeconds * 1000)) {
        throw "no HTTP connection arrived within ${TimeoutSeconds}s - did the enrollment child start?"
    }
    $client = $acceptTask.Result
    try {
        $stream = $client.GetStream()
        $stream.ReadTimeout = $TimeoutSeconds * 1000
        $buffer = New-Object byte[] 65536
        $received = New-Object System.IO.MemoryStream

        # Read headers, then the body - HttpClient's PostAsJsonAsync streams the JSON, so the
        # request arrives with Transfer-Encoding: chunked rather than Content-Length. The
        # enrollment body is pure ASCII (base64 + JSON punctuation), so chunk byte counts and
        # string offsets agree.
        $headerEnd = -1
        $contentLength = -1
        $chunked = $false
        while ($true) {
            $read = $stream.Read($buffer, 0, $buffer.Length)
            if ($read -le 0) { break }
            $received.Write($buffer, 0, $read)
            $text = [System.Text.Encoding]::UTF8.GetString($received.ToArray())
            if ($headerEnd -lt 0) {
                $headerEnd = $text.IndexOf("`r`n`r`n")
                if ($headerEnd -ge 0) {
                    foreach ($line in ($text.Substring(0, $headerEnd) -split "`r`n")) {
                        if ($line -match "^Content-Length:\s*(\d+)$") { $contentLength = [int]$Matches[1] }
                        if ($line -match "^Transfer-Encoding:\s*chunked$") { $chunked = $true }
                    }
                    if ($contentLength -lt 0 -and -not $chunked) { throw "enrollment POST carried neither Content-Length nor chunked encoding" }
                }
            }
            if ($headerEnd -ge 0) {
                $bodyText = $text.Substring($headerEnd + 4)
                if ($chunked) {
                    if ($bodyText.Contains("`r`n0`r`n")) { break }   # terminal zero-length chunk
                }
                elseif (($received.Length - ($headerEnd + 4)) -ge $contentLength) { break }
            }
        }
        if ($headerEnd -lt 0) { throw "connection closed before HTTP headers completed" }

        $full = [System.Text.Encoding]::UTF8.GetString($received.ToArray())
        $requestLine = ($full -split "`r`n")[0]
        $body = $full.Substring($headerEnd + 4)
        if ($chunked) {
            $raw = $body
            $body = ""
            $pos = 0
            while ($true) {
                $lineEnd = $raw.IndexOf("`r`n", $pos)
                if ($lineEnd -lt 0) { throw "malformed chunked body: no size line at offset $pos" }
                $size = [Convert]::ToInt32((($raw.Substring($pos, $lineEnd - $pos)) -split ";")[0], 16)
                if ($size -eq 0) { break }
                $body += $raw.Substring($lineEnd + 2, $size)
                $pos = $lineEnd + 2 + $size + 2
            }
        }

        $responseBytes = [System.Text.Encoding]::UTF8.GetBytes($ResponseJson)
        $header = "HTTP/1.1 200 OK`r`nContent-Type: application/json`r`nContent-Length: $($responseBytes.Length)`r`nConnection: close`r`n`r`n"
        $headerBytes = [System.Text.Encoding]::ASCII.GetBytes($header)
        $stream.Write($headerBytes, 0, $headerBytes.Length)
        $stream.Write($responseBytes, 0, $responseBytes.Length)
        $stream.Flush()

        return [pscustomobject]@{
            RequestLine = $requestLine
            Body        = ($body | ConvertFrom-Json)
        }
    }
    finally {
        $client.Close()
    }
}

New-Item -ItemType Directory -Force -Path $script:Sandbox | Out-Null

try {
    Write-Host ""
    Write-Host "identity helper under Windows PowerShell 5.1 ($($PSVersionTable.PSVersion), $($PSVersionTable.PSEdition))"

    Test-Case "this host genuinely lacks ImportFromPem - the reason the helper exists" {
        Assert-Equal -Expected "Desktop" -Actual $PSVersionTable.PSEdition `
            -Because "this suite must run on the engine the owner's machine runs"
        $method = [System.Security.Cryptography.ECDsa].GetMethod("ImportFromPem")
        Assert-True -Condition ($null -eq $method) `
            -Because "ECDsa.ImportFromPem exists on this host; the compatibility premise changed - re-evaluate, do not just delete this test"
    }

    $exe = Get-HelperExe
    Write-Host "  (service exe: $exe)"

    Test-Case "identity against an un-enrolled data dir refuses with exit 3 and creates NOTHING" {
        $dataDir = Join-Path $script:Sandbox "empty"
        New-Item -ItemType Directory -Force -Path $dataDir | Out-Null
        $result = Invoke-Helper -Exe $exe -DataDir $dataDir -Arguments @("identity")
        Assert-Equal -Expected 3 -Actual $result.ExitCode -Because "not-enrolled must be its own exit code, distinct from generic failure"
        Assert-True -Condition ($result.StdErr -match "not enrolled") -Because "the refusal must say why (stderr: $($result.StdErr))"
        Assert-Equal -Expected "" -Actual $result.StdOut.Trim() -Because "stdout is reserved for the JSON document; a refusal prints none"
        Assert-True -Condition (-not (Test-Path (Join-Path $dataDir "device.key"))) -Because "asking must never mint a key"
        Assert-True -Condition (-not (Test-Path (Join-Path $dataDir "state.json"))) -Because "asking must never mint state"
    }

    # ---- one REAL enrollment, then the restoration property -----------------------------
    $dataDir = Join-Path $script:Sandbox "enrolled"
    New-Item -ItemType Directory -Force -Path $dataDir | Out-Null
    $enrolledSpki = $null

    Test-Case "the real executable enrolls a real P-256 identity against this test's listener" {
        $listener = New-Object System.Net.Sockets.TcpListener([System.Net.IPAddress]::Loopback, 0)
        $listener.Start()
        try {
            $port = $listener.LocalEndpoint.Port

            $psi = New-Object System.Diagnostics.ProcessStartInfo
            $psi.FileName = $exe
            $psi.Arguments = ConvertTo-NativeArgumentLine -Arguments @(
                "enroll", "--broker-url", "http://127.0.0.1:$port", "--token", "test-enrollment-token", "--name", "qual-restore-test")
            $psi.UseShellExecute = $false
            $psi.RedirectStandardOutput = $true
            $psi.RedirectStandardError = $true
            $psi.CreateNoWindow = $true
            $psi.EnvironmentVariables["PAGENTOS_AGENT_DataDir"] = $dataDir
            $psi.EnvironmentVariables["PAGENTOS_AGENT_MachineMaterialMode"] = "developer"
            $child = [System.Diagnostics.Process]::Start($psi)
            $childOut = $child.StandardOutput.ReadToEndAsync()
            $childErr = $child.StandardError.ReadToEndAsync()

            $post = Receive-EnrollmentPost -Listener $listener -ResponseJson '{"device_id":"qual-restore-device"}'

            if (-not $child.WaitForExit(30000)) { try { $child.Kill() } catch { }; throw "enrollment child did not exit" }
            $child.WaitForExit()
            Assert-Equal -Expected 0 -Actual $child.ExitCode -Because "real enrollment must succeed (stderr: $($childErr.Result))"
            Assert-True -Condition ($post.RequestLine -match "POST /v1/devices/enroll") -Because "the exe must call the enrollment endpoint (got: $($post.RequestLine))"
            Assert-Equal -Expected "test-enrollment-token" -Actual $post.Body.token -Because "the one-time token travels in the body"
            Assert-True -Condition (-not [string]::IsNullOrWhiteSpace($post.Body.public_key_spki_b64)) -Because "enrollment must register a public key"
            [void][Convert]::FromBase64String($post.Body.public_key_spki_b64)   # must be valid base64
            $script:enrolledSpki = $post.Body.public_key_spki_b64

            Assert-True -Condition (Test-Path (Join-Path $dataDir "device.key")) -Because "a real private key must now exist"
            Assert-True -Condition (Test-Path (Join-Path $dataDir "state.json")) -Because "real enrollment state must now exist"
        }
        finally {
            $listener.Stop()
        }
    }

    Test-Case "identity returns the enrolled public key BYTE-FOR-BYTE - the restoration property" {
        Assert-True -Condition (-not [string]::IsNullOrWhiteSpace($script:enrolledSpki)) -Because "enrollment capture must have run first"
        $result = Invoke-Helper -Exe $exe -DataDir $dataDir -Arguments @("identity")
        Assert-Equal -Expected 0 -Actual $result.ExitCode -Because "an enrolled device answers (stderr: $($result.StdErr))"
        $doc = ConvertFrom-SingleJsonDocument -Text $result.StdOut -Activity "identity verb"
        Assert-Equal -Expected "qual-restore-device" -Actual $doc.device_id -Because "device_id comes from the enrolled state"
        Assert-Equal -Expected "qual-restore-test" -Actual $doc.name -Because "name comes from the enrolled state"
        Assert-Equal -Expected $script:enrolledSpki -Actual $doc.public_key_spki_b64 `
            -Because "restore_device_registration.py recreates the broker row from this value; it must equal the enrolled key exactly"
        Assert-True -Condition (-not [string]::IsNullOrWhiteSpace($doc.enrolled_at)) -Because "enrolled_at is part of the metadata"
        Assert-True -Condition ($result.StdOut -notmatch "PRIVATE") -Because "no private key material may appear on stdout"
        Assert-True -Condition ($result.StdOut.Trim() -notmatch "`n") -Because "stdout must be exactly one JSON document"
    }

    Test-Case "identity with the key file deleted refuses with exit 4 and does not re-mint" {
        $orphan = Join-Path $script:Sandbox "orphan"
        New-Item -ItemType Directory -Force -Path $orphan | Out-Null
        Copy-Item (Join-Path $dataDir "state.json") (Join-Path $orphan "state.json")
        $result = Invoke-Helper -Exe $exe -DataDir $orphan -Arguments @("identity")
        Assert-Equal -Expected 4 -Actual $result.ExitCode -Because "state-without-key is a distinct recovery situation"
        Assert-True -Condition ($result.StdErr -match "recovery") -Because "the refusal must name it (stderr: $($result.StdErr))"
        Assert-True -Condition (-not (Test-Path (Join-Path $orphan "device.key"))) -Because "a missing key must NEVER be silently replaced - that would orphan the broker registration"
    }
}
finally {
    Remove-Item -LiteralPath $script:Sandbox -Recurse -Force -ErrorAction SilentlyContinue
}

Write-Host ""
Write-Host "$($script:Passes) passed, $($script:Failures) failed"
exit $script:Failures
