/**
 * GENERATED — do not edit.
 *
 * `node scripts/web/sync-feature-matrix.mjs` rewrites this file from
 * `docs/product/PERSONALAGENTOS_V1_FEATURE_MATRIX.md`, which is the record this
 * product is measured against. The web test suite runs the same script with
 * `--check`, so an edit to the document that never reached here fails the gate
 * rather than leaving the owner reading a stale badge.
 */

export const MATRIX_VERSION = "2026-09-12";
export const MATRIX_BASE = "main @ 48dfcc3";

/** The IMPLEMENTATION_STATUS values the document actually uses. */
export const IMPL_CLASSES = [
  "BLOCKED_OWNER",
  "BLOCKED_PROVIDER",
  "DEFERRED",
  "DONE",
  "PARTIAL",
] as const;
export type ImplClass = (typeof IMPL_CLASSES)[number];

/** The PROOF_STATUS abbreviations, from the document's own LEGEND table. */
export const PROOF_CLASSES = [
  "BLK",
  "NYP",
  "PA",
  "PR",
  "PU",
  "PX",
] as const;
export type ProofClass = (typeof PROOF_CLASSES)[number];

/** What each abbreviation stands for — again the LEGEND's own words. */
export const PROOF_EXPANSION: Record<ProofClass, string> = {
  BLK: "BLOCKED",
  NYP: "NOT_YET_PROVEN",
  PA: "PROVEN_AUTOMATED",
  PR: "PROVEN_REAL",
  PU: "PROVIDER_UNAVAILABLE",
  PX: "PROVEN_PROXY",
};

export type MatrixSection = {
  key: string;
  title: string;
  from: number;
  to: number;
};

export const SECTIONS: readonly MatrixSection[] = [
  { key: "A", title: "BUG & RELIABILITY", from: 1, to: 30 },
  { key: "B", title: "MEMORY / PERSONAL INTELLIGENCE", from: 31, to: 62 },
  { key: "C", title: "SELF MODEL / WORLD MODEL", from: 63, to: 80 },
  { key: "D", title: "DIGITAL OPERATOR 2.0", from: 81, to: 130 },
  { key: "E", title: "FILE / DOCUMENT INTELLIGENCE", from: 131, to: 170 },
  { key: "F", title: "BROWSER / INTERNET / RESEARCH", from: 171, to: 210 },
  { key: "G", title: "VOICE / REALTIME", from: 211, to: 238 },
  { key: "H", title: "DEVICE-SIDE / AMBIENT VOICE", from: 239, to: 255 },
  { key: "I", title: "ALARM / ROUTINES / MORNING EXPERIENCE", from: 256, to: 299 },
  { key: "J", title: "PRESENCE / ACTIVE EYE / DISPLAY", from: 300, to: 334 },
  { key: "K", title: "MAIL / CALENDAR", from: 335, to: 366 },
  { key: "L", title: "NOTIFICATIONS / OWNER REACHABILITY", from: 367, to: 390 },
  { key: "M", title: "ARTIFACT FACTORY", from: 391, to: 416 },
  { key: "N", title: "APP FACTORY / CODE FACTORY", from: 417, to: 452 },
  { key: "O", title: "NATIVE APP FACTORY", from: 453, to: 480 },
  { key: "P", title: "CREATIVE / IMAGE", from: 481, to: 512 },
  { key: "Q", title: "3D / BLENDER / UNITY", from: 513, to: 534 },
  { key: "R", title: "EXECUTIVE AUTONOMY", from: 535, to: 560 },
  { key: "S", title: "CAPABILITY GENESIS", from: 561, to: 580 },
  { key: "T", title: "SELF-DEVELOPMENT ENGINE", from: 581, to: 625 },
  { key: "U", title: "BACKUP / RECOVERY", from: 626, to: 655 },
  { key: "V", title: "SECURITY / IDENTITY", from: 656, to: 684 },
  { key: "W", title: "WEB / COCKPIT / UX", from: 685, to: 725 },
  { key: "X", title: "NATURAL LANGUAGE / INTENT ROUTING", from: 726, to: 750 },
];

export type MatrixRow = {
  /** The permanent requirement id. Never renumbered. */
  id: number;
  /** The letter of the section heading the row appears under. */
  section: string;
  feature: string;
  impl: ImplClass;
  proof: ProofClass;
  /** The batch that owns the row, or `—`. */
  batch: string;
  /** True when the row cannot close without the owner doing something. */
  owner: boolean;
};

export const ROWS: readonly MatrixRow[] = [
  { id: 1, section: "A", feature: "Migration hatası release'i durdurur", impl: "DONE", proof: "PA", batch: "B01", owner: false },
  { id: 2, section: "A", feature: "Alembic sürümü release health'te doğrulanır", impl: "DONE", proof: "PR", batch: "B01", owner: false },
  { id: 3, section: "A", feature: "file.search mutlak path çözümü", impl: "DONE", proof: "PA", batch: "B03", owner: false },
  { id: 4, section: "A", feature: "App Factory manifest'leri device contract'a uyar", impl: "DONE", proof: "PA", batch: "B03", owner: false },
  { id: 5, section: "A", feature: "Fake device payload = gerçek wire shape", impl: "DONE", proof: "PA", batch: "B03", owner: false },
  { id: 6, section: "A", feature: "/v1/world/facts secret redaction", impl: "DONE", proof: "PA", batch: "B04", owner: false },
  { id: 7, section: "A", feature: "Log secret redaction", impl: "DONE", proof: "PA", batch: "B04", owner: false },
  { id: 8, section: "A", feature: "Health secret redaction", impl: "DONE", proof: "PA", batch: "B04", owner: false },
  { id: 9, section: "A", feature: "Dead Voice session sweeper", impl: "DONE", proof: "PA", batch: "B06", owner: false },
  { id: 10, section: "A", feature: "Takılmış research/task sweeper", impl: "DONE", proof: "PA", batch: "B06", owner: false },
  { id: 11, section: "A", feature: "Stale RUNNING/CREATED reconciliation", impl: "DONE", proof: "PA", batch: "B06", owner: false },
  { id: 12, section: "A", feature: "Temporal unavailable typed refusal", impl: "DONE", proof: "PA", batch: "—", owner: false },
  { id: 13, section: "A", feature: "Orphan research row cleanup", impl: "DONE", proof: "PA", batch: "B06", owner: false },
  { id: 14, section: "A", feature: "Retry loop'ları bounded", impl: "DONE", proof: "PA", batch: "B07", owner: false },
  { id: 15, section: "A", feature: "Push announcer bounded retry", impl: "DONE", proof: "PA", batch: "B07", owner: false },
  { id: 16, section: "A", feature: "Briefing announcer kuyruk kilidi yok", impl: "DONE", proof: "PA", batch: "B07", owner: false },
  { id: 17, section: "A", feature: "Research announcer bounded retry", impl: "DONE", proof: "PA", batch: "B07", owner: false },
  { id: 18, section: "A", feature: "Background loop health tek tek", impl: "DONE", proof: "PA", batch: "B07", owner: false },
  { id: 19, section: "A", feature: "Routine clock alt bileşen izolasyonu", impl: "DONE", proof: "PA", batch: "B07", owner: false },
  { id: 20, section: "A", feature: "Redis kritik sağlıktan çıkarılmalı (kullanılmıyorsa)", impl: "DONE", proof: "PA", batch: "—", owner: false },
  { id: 21, section: "A", feature: "Build/version provenance canonical", impl: "DONE", proof: "PR", batch: "B01", owner: false },
  { id: 22, section: "A", feature: "Aynı version altında build ayrımı", impl: "DONE", proof: "PR", batch: "B01", owner: false },
  { id: 23, section: "A", feature: "BUILD_STATE otomatik reconcile", impl: "DONE", proof: "PA", batch: "B01", owner: false },
  { id: 24, section: "A", feature: "Evidence-only-in-prose yasak", impl: "DONE", proof: "PA", batch: "B01", owner: false },
  { id: 25, section: "A", feature: "CI tüm kritik testleri kapsar", impl: "DONE", proof: "PA", batch: "B02", owner: false },
  { id: 26, section: "A", feature: "Web testleri CI'da", impl: "DONE", proof: "PR", batch: "B02", owner: false },
  { id: 27, section: "A", feature: "Web linter CI'da", impl: "DONE", proof: "PR", batch: "B02", owner: false },
  { id: 28, section: "A", feature: "PE reader testleri CI'da", impl: "DONE", proof: "PR", batch: "B02", owner: false },
  { id: 29, section: "A", feature: "PowerShell qualification CI'da", impl: "DONE", proof: "PR", batch: "B02", owner: false },
  { id: 30, section: "A", feature: "Mutation/falsification kritik contract'ta", impl: "DONE", proof: "PA", batch: "B02", owner: false },
  { id: 31, section: "B", feature: "memory.remember Voice tool", impl: "DONE", proof: "PA", batch: "B16", owner: false },
  { id: 32, section: "B", feature: "memory.search Voice tool", impl: "DONE", proof: "PA", batch: "B16", owner: false },
  { id: 33, section: "B", feature: "Preference extraction", impl: "DONE", proof: "PA", batch: "B16", owner: false },
  { id: 34, section: "B", feature: "Project/context extraction", impl: "DONE", proof: "PA", batch: "B16", owner: false },
  { id: 35, section: "B", feature: "\"bunu hatırla\"", impl: "DONE", proof: "PA", batch: "B16", owner: false },
  { id: 36, section: "B", feature: "\"bunu unut\"", impl: "DONE", proof: "PA", batch: "B16", owner: false },
  { id: 37, section: "B", feature: "\"bunu düzelt\"", impl: "DONE", proof: "PA", batch: "B16", owner: false },
  { id: 38, section: "B", feature: "\"bunu sabitle\"", impl: "DONE", proof: "PA", batch: "B16", owner: false },
  { id: 39, section: "B", feature: "Persona memory injection", impl: "DONE", proof: "PA", batch: "B17", owner: false },
  { id: 40, section: "B", feature: "Tool decision context injection", impl: "DONE", proof: "PA", batch: "B17", owner: false },
  { id: 41, section: "B", feature: "Top-k contextual retrieval", impl: "DONE", proof: "PA", batch: "B17", owner: false },
  { id: 42, section: "B", feature: "Memory provenance", impl: "DONE", proof: "PA", batch: "B17", owner: false },
  { id: 43, section: "B", feature: "Memory confidence", impl: "DONE", proof: "PA", batch: "B17", owner: false },
  { id: 44, section: "B", feature: "Conflict resolution", impl: "DONE", proof: "PA", batch: "B17", owner: false },
  { id: 45, section: "B", feature: "Explicit > inferred precedence", impl: "DONE", proof: "PA", batch: "B17", owner: false },
  { id: 46, section: "B", feature: "Project continuity", impl: "DONE", proof: "PA", batch: "B18", owner: false },
  { id: 47, section: "B", feature: "Person/entity relationships", impl: "DONE", proof: "PA", batch: "B18", owner: false },
  { id: 48, section: "B", feature: "Device-independent entity identity", impl: "DONE", proof: "PA", batch: "B18", owner: false },
  { id: 49, section: "B", feature: "Current/previous object focus", impl: "DONE", proof: "PA", batch: "B18", owner: false },
  { id: 50, section: "B", feature: "Recent task continuity", impl: "DONE", proof: "PA", batch: "B18", owner: false },
  { id: 51, section: "B", feature: "Real semantic embedding provider", impl: "DONE", proof: "PA", batch: "B37", owner: false },
  { id: 52, section: "B", feature: "Deterministic n-gram fallback", impl: "DONE", proof: "PR", batch: "—", owner: false },
  { id: 53, section: "B", feature: "Embedding provider selection", impl: "DONE", proof: "PA", batch: "B37", owner: false },
  { id: 54, section: "B", feature: "Re-index pipeline", impl: "DONE", proof: "PA", batch: "B37", owner: false },
  { id: 55, section: "B", feature: "Memory retention scheduler", impl: "DONE", proof: "PA", batch: "B17", owner: false },
  { id: 56, section: "B", feature: "Sensitive-data exclusion", impl: "DONE", proof: "PA", batch: "B17", owner: false },
  { id: 57, section: "B", feature: "Memory audit UI", impl: "DONE", proof: "PA", batch: "B37", owner: false },
  { id: 58, section: "B", feature: "Pin/unpin UI", impl: "DONE", proof: "PA", batch: "B37", owner: false },
  { id: 59, section: "B", feature: "Forget UI", impl: "DONE", proof: "PA", batch: "B37", owner: false },
  { id: 60, section: "B", feature: "Correction UI", impl: "DONE", proof: "PA", batch: "B37", owner: false },
  { id: 61, section: "B", feature: "\"Neden bunu hatırladın?\"", impl: "DONE", proof: "PA", batch: "B16", owner: false },
  { id: 62, section: "B", feature: "Memory usage receipts", impl: "DONE", proof: "PA", batch: "B16", owner: false },
  { id: 63, section: "C", feature: "Runtime/source correlation", impl: "DONE", proof: "PA", batch: "B19", owner: false },
  { id: 64, section: "C", feature: "Deployed SHA awareness", impl: "DONE", proof: "PA", batch: "B19", owner: false },
  { id: 65, section: "C", feature: "Windows build awareness", impl: "DONE", proof: "PA", batch: "B19", owner: false },
  { id: 66, section: "C", feature: "Device capability awareness", impl: "DONE", proof: "PA", batch: "B19", owner: false },
  { id: 67, section: "C", feature: "World model terminal-state accuracy", impl: "DONE", proof: "PA", batch: "B06", owner: false },
  { id: 68, section: "C", feature: "READY research running sayılmasın", impl: "DONE", proof: "PA", batch: "B06", owner: false },
  { id: 69, section: "C", feature: "Stuck task detection", impl: "DONE", proof: "PA", batch: "B06", owner: false },
  { id: 70, section: "C", feature: "Ledger duplicate Voice event prevention", impl: "DONE", proof: "PA", batch: "B06", owner: false },
  { id: 71, section: "C", feature: "Experience Engine scheduler", impl: "DONE", proof: "PA", batch: "B18", owner: false },
  { id: 72, section: "C", feature: "Activity to lesson extraction", impl: "DONE", proof: "PA", batch: "B18", owner: false },
  { id: 73, section: "C", feature: "Lesson to memory integration", impl: "DONE", proof: "PA", batch: "B18", owner: false },
  { id: 74, section: "C", feature: "System health explanation", impl: "DONE", proof: "PA", batch: "B19", owner: false },
  { id: 75, section: "C", feature: "\"Şu an ne yapıyorsun?\"", impl: "DONE", proof: "PA", batch: "B06", owner: false },
  { id: 76, section: "C", feature: "\"Nerede takıldın?\"", impl: "DONE", proof: "PA", batch: "B19", owner: false },
  { id: 77, section: "C", feature: "\"Son bug neydi?\"", impl: "DONE", proof: "PA", batch: "B19", owner: false },
  { id: 78, section: "C", feature: "\"Hangi özelliklerin çalışmıyor?\"", impl: "DONE", proof: "PA", batch: "B19", owner: false },
  { id: 79, section: "C", feature: "Self-diagnostic summary", impl: "DONE", proof: "PA", batch: "B19", owner: false },
  { id: 80, section: "C", feature: "Self-model stale-data detection", impl: "DONE", proof: "PA", batch: "B19", owner: false },
  { id: 81, section: "D", feature: "App launch", impl: "DONE", proof: "PR", batch: "—", owner: false },
  { id: 82, section: "D", feature: "App close", impl: "DONE", proof: "PA", batch: "B30", owner: false },
  { id: 83, section: "D", feature: "Window activate", impl: "DONE", proof: "PA", batch: "—", owner: false },
  { id: 84, section: "D", feature: "Window move", impl: "DONE", proof: "PA", batch: "B30", owner: false },
  { id: 85, section: "D", feature: "Window resize", impl: "DONE", proof: "PA", batch: "B30", owner: false },
  { id: 86, section: "D", feature: "Minimize", impl: "DONE", proof: "PA", batch: "B30", owner: false },
  { id: 87, section: "D", feature: "Maximize", impl: "DONE", proof: "PA", batch: "B30", owner: false },
  { id: 88, section: "D", feature: "Restore", impl: "DONE", proof: "PA", batch: "B30", owner: false },
  { id: 89, section: "D", feature: "Window list", impl: "DONE", proof: "PA", batch: "—", owner: false },
  { id: 90, section: "D", feature: "Current foreground read", impl: "DONE", proof: "PA", batch: "—", owner: false },
  { id: 91, section: "D", feature: "Keyboard typing", impl: "DONE", proof: "PA", batch: "B28", owner: false },
  { id: 92, section: "D", feature: "Single key press", impl: "DONE", proof: "PA", batch: "B28", owner: false },
  { id: 93, section: "D", feature: "Keyboard shortcuts", impl: "DONE", proof: "PA", batch: "B28", owner: false },
  { id: 94, section: "D", feature: "Mouse move", impl: "DONE", proof: "PA", batch: "B28", owner: false },
  { id: 95, section: "D", feature: "Mouse click", impl: "DONE", proof: "PA", batch: "B28", owner: false },
  { id: 96, section: "D", feature: "Double click", impl: "DONE", proof: "PA", batch: "B28", owner: false },
  { id: 97, section: "D", feature: "Right click", impl: "DONE", proof: "PA", batch: "B28", owner: false },
  { id: 98, section: "D", feature: "Scroll", impl: "DONE", proof: "PA", batch: "B28", owner: false },
  { id: 99, section: "D", feature: "UIA tree inspect", impl: "DONE", proof: "PA", batch: "B29", owner: false },
  { id: 100, section: "D", feature: "UIA button invoke", impl: "DONE", proof: "PA", batch: "B29", owner: false },
  { id: 101, section: "D", feature: "UIA set value", impl: "DONE", proof: "PA", batch: "B29", owner: false },
  { id: 102, section: "D", feature: "UIA read text", impl: "DONE", proof: "PA", batch: "B29", owner: false },
  { id: 103, section: "D", feature: "UIA select item", impl: "DONE", proof: "PA", batch: "B29", owner: false },
  { id: 104, section: "D", feature: "Screenshot capture", impl: "DONE", proof: "PA", batch: "B28", owner: false },
  { id: 105, section: "D", feature: "Screenshot understanding", impl: "DONE", proof: "PU", batch: "B29", owner: false },
  { id: 106, section: "D", feature: "Vision-based fallback", impl: "DONE", proof: "PA", batch: "B39", owner: false },
  { id: 107, section: "D", feature: "Coordinate only as last resort", impl: "DONE", proof: "PA", batch: "B28", owner: false },
  { id: 108, section: "D", feature: "FocusGuard", impl: "DONE", proof: "PA", batch: "—", owner: false },
  { id: 109, section: "D", feature: "Secret typing refusal", impl: "DONE", proof: "PA", batch: "B28", owner: false },
  { id: 110, section: "D", feature: "Per-action receipt", impl: "DONE", proof: "PA", batch: "B28", owner: false },
  { id: 111, section: "D", feature: "Postcondition verification", impl: "DONE", proof: "PA", batch: "B29", owner: false },
  { id: 112, section: "D", feature: "Observe-Decide-Act-Verify", impl: "DONE", proof: "PA", batch: "B39", owner: false },
  { id: 113, section: "D", feature: "Dynamic replanning", impl: "DONE", proof: "PA", batch: "B39", owner: false },
  { id: 114, section: "D", feature: "Retry by failure taxonomy", impl: "DONE", proof: "PA", batch: "B39", owner: false },
  { id: 115, section: "D", feature: "Recovery/escalation", impl: "DONE", proof: "PA", batch: "B39", owner: false },
  { id: 116, section: "D", feature: "App-specific adapters", impl: "DONE", proof: "PA", batch: "B29", owner: false },
  { id: 117, section: "D", feature: "6'dan fazla açılabilir uygulama", impl: "DONE", proof: "PA", batch: "B30", owner: false },
  { id: 118, section: "D", feature: "Safe terminal expansion", impl: "DONE", proof: "PA", batch: "B30", owner: false },
  { id: 119, section: "D", feature: "Process inspect", impl: "DONE", proof: "PA", batch: "B30", owner: false },
  { id: 120, section: "D", feature: "Process stop with policy", impl: "DONE", proof: "PA", batch: "B30", owner: false },
  { id: 121, section: "D", feature: "Service inspect", impl: "DONE", proof: "PA", batch: "B30", owner: false },
  { id: 122, section: "D", feature: "Service restart with policy", impl: "DONE", proof: "PA", batch: "B30", owner: false },
  { id: 123, section: "D", feature: "Windows Settings navigation", impl: "DONE", proof: "PA", batch: "B39", owner: false },
  { id: 124, section: "D", feature: "File Explorer operations", impl: "DONE", proof: "PA", batch: "B39", owner: false },
  { id: 125, section: "D", feature: "Office app interaction", impl: "DONE", proof: "PA", batch: "B39", owner: false },
  { id: 126, section: "D", feature: "IDE interaction", impl: "DONE", proof: "PA", batch: "B39", owner: false },
  { id: 127, section: "D", feature: "Browser + desktop mixed plan", impl: "DONE", proof: "PA", batch: "B39", owner: false },
  { id: 128, section: "D", feature: "Multi-step task persistence", impl: "DONE", proof: "PA", batch: "B39", owner: false },
  { id: 129, section: "D", feature: "Operator pause/cancel", impl: "DONE", proof: "PA", batch: "B39", owner: false },
  { id: 130, section: "D", feature: "\"Show me before acting\"", impl: "DONE", proof: "PA", batch: "B39", owner: false },
  { id: 131, section: "E", feature: "PDF read", impl: "DONE", proof: "PA", batch: "—", owner: false },
  { id: 132, section: "E", feature: "DOCX read", impl: "DONE", proof: "PA", batch: "—", owner: false },
  { id: 133, section: "E", feature: "XLSX read", impl: "DONE", proof: "PA", batch: "—", owner: false },
  { id: 134, section: "E", feature: "PPTX read", impl: "DONE", proof: "PA", batch: "—", owner: false },
  { id: 135, section: "E", feature: "CSV read", impl: "DONE", proof: "PA", batch: "—", owner: false },
  { id: 136, section: "E", feature: "JSON read", impl: "DONE", proof: "PA", batch: "—", owner: false },
  { id: 137, section: "E", feature: "Markdown read", impl: "DONE", proof: "PA", batch: "—", owner: false },
  { id: 138, section: "E", feature: "Source code read", impl: "DONE", proof: "PA", batch: "—", owner: false },
  { id: 139, section: "E", feature: "Image metadata read", impl: "DONE", proof: "PA", batch: "B32", owner: false },
  { id: 140, section: "E", feature: "OCR", impl: "DONE", proof: "PA", batch: "B32", owner: false },
  { id: 141, section: "E", feature: "Image text extraction", impl: "DONE", proof: "PA", batch: "B32", owner: false },
  { id: 142, section: "E", feature: "Archive inspect", impl: "DONE", proof: "PA", batch: "B32", owner: false },
  { id: 143, section: "E", feature: "EPUB read", impl: "DONE", proof: "PA", batch: "B52", owner: false },
  { id: 144, section: "E", feature: "RTF read", impl: "DONE", proof: "PA", batch: "B52", owner: false },
  { id: 145, section: "E", feature: "ODT read", impl: "DONE", proof: "PA", batch: "B52", owner: false },
  { id: 146, section: "E", feature: "Legacy Office formats", impl: "DONE", proof: "PA", batch: "B52", owner: false },
  { id: 147, section: "E", feature: "File metadata search", impl: "DONE", proof: "PA", batch: "B03", owner: false },
  { id: 148, section: "E", feature: "Full text search", impl: "DONE", proof: "PA", batch: "B32", owner: false },
  { id: 149, section: "E", feature: "Semantic document search", impl: "DONE", proof: "PA", batch: "B37", owner: false },
  { id: 150, section: "E", feature: "File deduplication", impl: "DONE", proof: "PA", batch: "B32", owner: false },
  { id: 151, section: "E", feature: "Duplicate detection", impl: "DONE", proof: "PA", batch: "B32", owner: false },
  { id: 152, section: "E", feature: "File preview", impl: "DONE", proof: "PA", batch: "B32", owner: false },
  { id: 153, section: "E", feature: "File edit", impl: "DONE", proof: "PA", batch: "B34", owner: false },
  { id: 154, section: "E", feature: "File write", impl: "DONE", proof: "PA", batch: "B34", owner: false },
  { id: 155, section: "E", feature: "File append", impl: "DONE", proof: "PA", batch: "B34", owner: false },
  { id: 156, section: "E", feature: "File rename", impl: "DONE", proof: "PA", batch: "B34", owner: false },
  { id: 157, section: "E", feature: "File move", impl: "DONE", proof: "PA", batch: "B34", owner: false },
  { id: 158, section: "E", feature: "File copy", impl: "DONE", proof: "PA", batch: "B34", owner: false },
  { id: 159, section: "E", feature: "File delete", impl: "DONE", proof: "PA", batch: "B34", owner: false },
  { id: 160, section: "E", feature: "Undo journal", impl: "DONE", proof: "PA", batch: "B34", owner: false },
  { id: 161, section: "E", feature: "Trash/recycle integration", impl: "DONE", proof: "PA", batch: "B34", owner: false },
  { id: 162, section: "E", feature: "Mutation receipt", impl: "DONE", proof: "PA", batch: "B34", owner: false },
  { id: 163, section: "E", feature: "Before/after hash", impl: "DONE", proof: "PA", batch: "B34", owner: false },
  { id: 164, section: "E", feature: "Document version history", impl: "DONE", proof: "PA", batch: "B34", owner: false },
  { id: 165, section: "E", feature: "Safe atomic write", impl: "DONE", proof: "PA", batch: "B34", owner: false },
  { id: 166, section: "E", feature: "Owner approval by risk", impl: "DONE", proof: "PA", batch: "B34", owner: false },
  { id: 167, section: "E", feature: "\"Bu dosyayı düzenle\"", impl: "DONE", proof: "PA", batch: "B34", owner: false },
  { id: 168, section: "E", feature: "\"Şu klasördeki dosyaları özetle\"", impl: "DONE", proof: "PA", batch: "B03", owner: false },
  { id: 169, section: "E", feature: "\"Bu iki dokümanı karşılaştır\"", impl: "DONE", proof: "PA", batch: "B32", owner: false },
  { id: 170, section: "E", feature: "\"Bu belgeyi güncelle ve kaydet\"", impl: "DONE", proof: "PA", batch: "B34", owner: false },
  { id: 171, section: "F", feature: "Managed Chrome", impl: "DONE", proof: "PR", batch: "—", owner: false },
  { id: 172, section: "F", feature: "Owner Chrome reuse", impl: "DONE", proof: "PA", batch: "B31", owner: false },
  { id: 173, section: "F", feature: "Session reuse", impl: "DONE", proof: "PA", batch: "B31", owner: false },
  { id: 174, section: "F", feature: "Search", impl: "DONE", proof: "PR", batch: "—", owner: false },
  { id: 175, section: "F", feature: "Navigation", impl: "DONE", proof: "PR", batch: "—", owner: false },
  { id: 176, section: "F", feature: "DOM inspect", impl: "DONE", proof: "PA", batch: "—", owner: false },
  { id: 177, section: "F", feature: "DOM click", impl: "DONE", proof: "PA", batch: "—", owner: false },
  { id: 178, section: "F", feature: "DOM text entry", impl: "DONE", proof: "PA", batch: "—", owner: false },
  { id: 179, section: "F", feature: "Form fill", impl: "DONE", proof: "PA", batch: "—", owner: false },
  { id: 180, section: "F", feature: "Download", impl: "DONE", proof: "PA", batch: "B31", owner: false },
  { id: 181, section: "F", feature: "Upload", impl: "DONE", proof: "PA", batch: "B31", owner: false },
  { id: 182, section: "F", feature: "Multi-tab handling", impl: "DONE", proof: "PA", batch: "—", owner: false },
  { id: 183, section: "F", feature: "Tab focus", impl: "DONE", proof: "PA", batch: "—", owner: false },
  { id: 184, section: "F", feature: "Browser screenshot", impl: "DONE", proof: "PA", batch: "—", owner: false },
  { id: 185, section: "F", feature: "CAPTCHA detection", impl: "DONE", proof: "PA", batch: "—", owner: false },
  { id: 186, section: "F", feature: "CAPTCHA bypass yasak", impl: "DONE", proof: "PA", batch: "—", owner: false },
  { id: 187, section: "F", feature: "SSRF guard", impl: "DONE", proof: "PA", batch: "—", owner: false },
  { id: 188, section: "F", feature: "Private network guard", impl: "DONE", proof: "PA", batch: "—", owner: false },
  { id: 189, section: "F", feature: "Owner research authorization", impl: "DONE", proof: "PA", batch: "—", owner: false },
  { id: 190, section: "F", feature: "QUICK research", impl: "DONE", proof: "PR", batch: "—", owner: false },
  { id: 191, section: "F", feature: "STANDARD research", impl: "DONE", proof: "PR", batch: "—", owner: false },
  { id: 192, section: "F", feature: "DEEP research", impl: "DONE", proof: "PA", batch: "B31", owner: false },
  { id: 193, section: "F", feature: "Source ranking", impl: "DONE", proof: "PA", batch: "—", owner: false },
  { id: 194, section: "F", feature: "Domain diversity", impl: "DONE", proof: "PA", batch: "—", owner: false },
  { id: 195, section: "F", feature: "Challenge skip", impl: "DONE", proof: "PA", batch: "—", owner: false },
  { id: 196, section: "F", feature: "Source cooldown", impl: "DONE", proof: "PA", batch: "—", owner: false },
  { id: 197, section: "F", feature: "Citation binding", impl: "DONE", proof: "PA", batch: "—", owner: false },
  { id: 198, section: "F", feature: "Research focus/current report", impl: "DONE", proof: "PA", batch: "B31", owner: false },
  { id: 199, section: "F", feature: "Previous report references", impl: "DONE", proof: "PA", batch: "B31", owner: false },
  { id: 200, section: "F", feature: "\"Bunu teknik anlat\"", impl: "DONE", proof: "PA", batch: "B31", owner: false },
  { id: 201, section: "F", feature: "\"Bir önceki araştırmayı aç\"", impl: "DONE", proof: "PA", batch: "B31", owner: false },
  { id: 202, section: "F", feature: "Research cancel", impl: "DONE", proof: "PA", batch: "B31", owner: false },
  { id: 203, section: "F", feature: "Research pause", impl: "DONE", proof: "PA", batch: "B31", owner: false },
  { id: 204, section: "F", feature: "Research resume", impl: "DONE", proof: "PA", batch: "B31", owner: false },
  { id: 205, section: "F", feature: "Temporal typed failures", impl: "DONE", proof: "PA", batch: "—", owner: false },
  { id: 206, section: "F", feature: "Orphan cleanup", impl: "DONE", proof: "PA", batch: "B06", owner: false },
  { id: 207, section: "F", feature: "Provider fallback transparency", impl: "DONE", proof: "PA", batch: "B31", owner: false },
  { id: 208, section: "F", feature: "Result-first narration", impl: "DONE", proof: "PA", batch: "—", owner: false },
  { id: 209, section: "F", feature: "Technical mode", impl: "DONE", proof: "PA", batch: "B31", owner: false },
  { id: 210, section: "F", feature: "Research history UI", impl: "DONE", proof: "PA", batch: "B31", owner: false },
  { id: 211, section: "G", feature: "Browser Voice WebRTC", impl: "DONE", proof: "PR", batch: "—", owner: false },
  { id: 212, section: "G", feature: "Stable data channel", impl: "DONE", proof: "PR", batch: "—", owner: false },
  { id: 213, section: "G", feature: "Barge-in", impl: "DONE", proof: "PA", batch: "—", owner: false },
  { id: 214, section: "G", feature: "Semantic VAD", impl: "DONE", proof: "PA", batch: "—", owner: false },
  { id: 215, section: "G", feature: "Noise suppression", impl: "DONE", proof: "PA", batch: "B20", owner: false },
  { id: 216, section: "G", feature: "Echo cancellation", impl: "DONE", proof: "PA", batch: "B20", owner: false },
  { id: 217, section: "G", feature: "Mic sensitivity modes", impl: "DONE", proof: "PA", batch: "B20", owner: false },
  { id: 218, section: "G", feature: "Reconnect", impl: "DONE", proof: "PA", batch: "B20", owner: false },
  { id: 219, section: "G", feature: "Dead session cleanup", impl: "DONE", proof: "PA", batch: "B06", owner: false },
  { id: 220, section: "G", feature: "Session TTL", impl: "DONE", proof: "PA", batch: "B06", owner: false },
  { id: 221, section: "G", feature: "False LISTENING prevention", impl: "DONE", proof: "PA", batch: "B20", owner: false },
  { id: 222, section: "G", feature: "Mic track loss detection", impl: "DONE", proof: "PA", batch: "B20", owner: false },
  { id: 223, section: "G", feature: "Provider 60-min limit handling", impl: "DONE", proof: "PA", batch: "B20", owner: false },
  { id: 224, section: "G", feature: "Long-form narration", impl: "DONE", proof: "PA", batch: "B21", owner: false },
  { id: 225, section: "G", feature: "Narration queue", impl: "DONE", proof: "PA", batch: "B21", owner: false },
  { id: 226, section: "G", feature: "Read-ahead", impl: "DONE", proof: "PA", batch: "B21", owner: false },
  { id: 227, section: "G", feature: "Pause/resume narration", impl: "DONE", proof: "PA", batch: "B21", owner: false },
  { id: 228, section: "G", feature: "Pronunciation dictionary", impl: "DONE", proof: "PA", batch: "B21", owner: false },
  { id: 229, section: "G", feature: "Pronunciation in assistant speech", impl: "DONE", proof: "PA", batch: "B21", owner: false },
  { id: 230, section: "G", feature: "Turkish number pronunciation", impl: "DONE", proof: "PA", batch: "B21", owner: false },
  { id: 231, section: "G", feature: "Speaking state = real playback", impl: "DONE", proof: "PA", batch: "B20", owner: false },
  { id: 232, section: "G", feature: "RMS only drives animation", impl: "DONE", proof: "PA", batch: "—", owner: false },
  { id: 233, section: "G", feature: "Text fallback on provider failure", impl: "DONE", proof: "PA", batch: "B20", owner: false },
  { id: 234, section: "G", feature: "TTS fallback policy", impl: "DONE", proof: "PA", batch: "B20", owner: false },
  { id: 235, section: "G", feature: "Provider-unavailable UI", impl: "DONE", proof: "PA", batch: "B20", owner: false },
  { id: 236, section: "G", feature: "Voice diagnostics", impl: "DONE", proof: "PA", batch: "B20", owner: false },
  { id: 237, section: "G", feature: "\"Teknik anlat\" mode", impl: "DONE", proof: "PA", batch: "B21", owner: false },
  { id: 238, section: "G", feature: "Voice activity history", impl: "DONE", proof: "PA", batch: "B20", owner: false },
  { id: 239, section: "H", feature: "Device-side microphone provider", impl: "DONE", proof: "PA", batch: "B47", owner: true },
  { id: 240, section: "H", feature: "Browser-independent listening", impl: "DONE", proof: "PA", batch: "B47", owner: true },
  { id: 241, section: "H", feature: "Wake word", impl: "PARTIAL", proof: "PA", batch: "B47", owner: true },
  { id: 242, section: "H", feature: "Wake-word enable/disable", impl: "DONE", proof: "PA", batch: "B47", owner: false },
  { id: 243, section: "H", feature: "Push-to-talk fallback", impl: "DONE", proof: "PA", batch: "B47", owner: false },
  { id: 244, section: "H", feature: "Local VAD", impl: "DONE", proof: "PA", batch: "B47", owner: false },
  { id: 245, section: "H", feature: "Speaker verification", impl: "PARTIAL", proof: "PA", batch: "B05", owner: false },
  { id: 246, section: "H", feature: "Trusted-device check", impl: "DONE", proof: "PA", batch: "B05", owner: false },
  { id: 247, section: "H", feature: "Speaker-confidence threshold", impl: "PARTIAL", proof: "PA", batch: "B05", owner: false },
  { id: 248, section: "H", feature: "Sensitive-command higher threshold", impl: "PARTIAL", proof: "PA", batch: "B05", owner: false },
  { id: 249, section: "H", feature: "Raw voice not archived", impl: "DONE", proof: "PA", batch: "—", owner: false },
  { id: 250, section: "H", feature: "Device-local Voice startup", impl: "DONE", proof: "PA", batch: "B47", owner: true },
  { id: 251, section: "H", feature: "Voice service restart recovery", impl: "DONE", proof: "PA", batch: "B47", owner: false },
  { id: 252, section: "H", feature: "Voice process health", impl: "DONE", proof: "PA", batch: "B47", owner: false },
  { id: 253, section: "H", feature: "Offline command subset", impl: "PARTIAL", proof: "PA", batch: "B47", owner: true },
  { id: 254, section: "H", feature: "Voice privacy indicator", impl: "DONE", proof: "PA", batch: "B47", owner: false },
  { id: 255, section: "H", feature: "Hardware mic mute awareness", impl: "PARTIAL", proof: "PA", batch: "B47", owner: true },
  { id: 256, section: "I", feature: "Durable alarm create", impl: "DONE", proof: "PR", batch: "—", owner: false },
  { id: 257, section: "I", feature: "Alarm cancel", impl: "DONE", proof: "PA", batch: "—", owner: false },
  { id: 258, section: "I", feature: "Alarm list", impl: "DONE", proof: "PA", batch: "—", owner: false },
  { id: 259, section: "I", feature: "Snooze", impl: "DONE", proof: "PA", batch: "B13, B47", owner: false },
  { id: 260, section: "I", feature: "Stop", impl: "DONE", proof: "PA", batch: "—", owner: false },
  { id: 261, section: "I", feature: "Weekday recurring alarm", impl: "DONE", proof: "PA", batch: "B14", owner: false },
  { id: 262, section: "I", feature: "Custom recurring alarm", impl: "DONE", proof: "PA", batch: "B14", owner: false },
  { id: 263, section: "I", feature: "Local device backup alarm", impl: "DONE", proof: "PA", batch: "—", owner: false },
  { id: 264, section: "I", feature: "Cloud-independent firing", impl: "DONE", proof: "PA", batch: "—", owner: false },
  { id: 265, section: "I", feature: "Display wake", impl: "DONE", proof: "PR", batch: "—", owner: false },
  { id: 266, section: "I", feature: "Saved YouTube wake song", impl: "DONE", proof: "PR", batch: "—", owner: false },
  { id: 267, section: "I", feature: "Safe tone fallback", impl: "DONE", proof: "PA", batch: "B13", owner: false },
  { id: 268, section: "I", feature: "Volume ramp", impl: "DONE", proof: "PA", batch: "—", owner: false },
  { id: 269, section: "I", feature: "Media duck", impl: "DONE", proof: "PA", batch: "B13", owner: false },
  { id: 270, section: "I", feature: "Greeting", impl: "DONE", proof: "PA", batch: "B15", owner: false },
  { id: 271, section: "I", feature: "Current time", impl: "DONE", proof: "PA", batch: "B15", owner: false },
  { id: 272, section: "I", feature: "Weather", impl: "DONE", proof: "PA", batch: "B15", owner: false },
  { id: 273, section: "I", feature: "Location", impl: "DONE", proof: "PA", batch: "B15", owner: false },
  { id: 274, section: "I", feature: "System status", impl: "DONE", proof: "PA", batch: "B15", owner: false },
  { id: 275, section: "I", feature: "Overnight task summary", impl: "DONE", proof: "PA", batch: "B15", owner: false },
  { id: 276, section: "I", feature: "Research completion summary", impl: "DONE", proof: "PA", batch: "B15", owner: false },
  { id: 277, section: "I", feature: "Calendar summary", impl: "DONE", proof: "PA", batch: "B46", owner: false },
  { id: 278, section: "I", feature: "Mail summary", impl: "DONE", proof: "PA", batch: "B45", owner: false },
  { id: 279, section: "I", feature: "News summary", impl: "DONE", proof: "PA", batch: "B15", owner: false },
  { id: 280, section: "I", feature: "Morning briefing", impl: "DONE", proof: "PA", batch: "B15", owner: false },
  { id: 281, section: "I", feature: "Browser-independent morning briefing", impl: "DONE", proof: "BLK", batch: "B15", owner: false },
  { id: 282, section: "I", feature: "Alarm fired receipt to Cloud", impl: "DONE", proof: "PA", batch: "B13", owner: false },
  { id: 283, section: "I", feature: "Prevent duplicate firing", impl: "DONE", proof: "PA", batch: "B13", owner: false },
  { id: 284, section: "I", feature: "Single late threshold", impl: "DONE", proof: "PA", batch: "B13", owner: false },
  { id: 285, section: "I", feature: "Alarm history", impl: "DONE", proof: "PA", batch: "B13", owner: false },
  { id: 286, section: "I", feature: "Alarm test mode", impl: "DONE", proof: "PA", batch: "B13", owner: false },
  { id: 287, section: "I", feature: "routine.create", impl: "DONE", proof: "PA", batch: "B14", owner: false },
  { id: 288, section: "I", feature: "routine.list", impl: "DONE", proof: "PA", batch: "B14", owner: false },
  { id: 289, section: "I", feature: "routine.cancel", impl: "DONE", proof: "PA", batch: "B14", owner: false },
  { id: 290, section: "I", feature: "routine.pause", impl: "DONE", proof: "PA", batch: "B14", owner: false },
  { id: 291, section: "I", feature: "routine.resume", impl: "DONE", proof: "PA", batch: "B14", owner: false },
  { id: 292, section: "I", feature: "Presence-trigger routine", impl: "DONE", proof: "PA", batch: "B14", owner: false },
  { id: 293, section: "I", feature: "Schedule-trigger routine", impl: "DONE", proof: "PA", batch: "B14", owner: false },
  { id: 294, section: "I", feature: "Condition-trigger routine", impl: "DONE", proof: "PA", batch: "B14", owner: false },
  { id: 295, section: "I", feature: "Routine panel in Cockpit", impl: "DONE", proof: "PA", batch: "B14", owner: false },
  { id: 296, section: "I", feature: "Natural-language recurring routines", impl: "DONE", proof: "PA", batch: "B14", owner: false },
  { id: 297, section: "I", feature: "\"Her sabah 08:00...\"", impl: "DONE", proof: "PA", batch: "B14", owner: false },
  { id: 298, section: "I", feature: "\"Evden çıkınca...\"", impl: "DONE", proof: "PA", batch: "B14", owner: false },
  { id: 299, section: "I", feature: "\"Bilgisayar boşta kalınca...\"", impl: "DONE", proof: "PA", batch: "B14", owner: false },
  { id: 300, section: "J", feature: "Camera open", impl: "PARTIAL", proof: "PA", batch: "B48", owner: false },
  { id: 301, section: "J", feature: "Camera close", impl: "DONE", proof: "PA", batch: "B48", owner: false },
  { id: 302, section: "J", feature: "Camera reopen", impl: "DONE", proof: "PA", batch: "B48", owner: false },
  { id: 303, section: "J", feature: "Camera privacy state", impl: "DONE", proof: "PA", batch: "B48", owner: false },
  { id: 304, section: "J", feature: "PRESENT", impl: "DONE", proof: "PR", batch: "—", owner: false },
  { id: 305, section: "J", feature: "AWAY", impl: "DONE", proof: "PR", batch: "—", owner: false },
  { id: 306, section: "J", feature: "RETURNED", impl: "DONE", proof: "PR", batch: "—", owner: false },
  { id: 307, section: "J", feature: "RESTING", impl: "DONE", proof: "PA", batch: "B48", owner: false },
  { id: 308, section: "J", feature: "LIKELY_ASLEEP", impl: "DONE", proof: "PA", batch: "B48", owner: false },
  { id: 309, section: "J", feature: "UNKNOWN", impl: "DONE", proof: "PR", batch: "—", owner: false },
  { id: 310, section: "J", feature: "Temporal confidence", impl: "DONE", proof: "PA", batch: "B48", owner: false },
  { id: 311, section: "J", feature: "Input activity fusion", impl: "DONE", proof: "PR", batch: "—", owner: false },
  { id: 312, section: "J", feature: "Time-of-day fusion", impl: "DONE", proof: "PA", batch: "B48", owner: false },
  { id: 313, section: "J", feature: "Owner preference fusion", impl: "DONE", proof: "PA", batch: "B48", owner: false },
  { id: 314, section: "J", feature: "Camera failure is not asleep", impl: "DONE", proof: "PA", batch: "—", owner: false },
  { id: 315, section: "J", feature: "UNKNOWN keeps display on", impl: "DONE", proof: "PA", batch: "—", owner: false },
  { id: 316, section: "J", feature: "Keyboard wake", impl: "DONE", proof: "PR", batch: "—", owner: false },
  { id: 317, section: "J", feature: "Mouse wake", impl: "DONE", proof: "PR", batch: "—", owner: false },
  { id: 318, section: "J", feature: "Display off", impl: "DONE", proof: "PR", batch: "—", owner: false },
  { id: 319, section: "J", feature: "Display wake", impl: "DONE", proof: "PR", batch: "—", owner: false },
  { id: 320, section: "J", feature: "Multiple-monitor power", impl: "PARTIAL", proof: "PR", batch: "B48", owner: false },
  { id: 321, section: "J", feature: "No topology/resolution modification", impl: "DONE", proof: "PA", batch: "—", owner: false },
  { id: 322, section: "J", feature: "Alarm wake precedence", impl: "DONE", proof: "PA", batch: "—", owner: false },
  { id: 323, section: "J", feature: "Holdoff after input", impl: "DONE", proof: "PA", batch: "—", owner: false },
  { id: 324, section: "J", feature: "Holdoff after alarm", impl: "DONE", proof: "PA", batch: "—", owner: false },
  { id: 325, section: "J", feature: "Holdoff after explicit wake", impl: "DONE", proof: "PA", batch: "—", owner: false },
  { id: 326, section: "J", feature: "Device-local presence provider", impl: "DONE", proof: "PA", batch: "B48", owner: false },
  { id: 327, section: "J", feature: "Browser-independent camera provider", impl: "PARTIAL", proof: "PA", batch: "B48", owner: false },
  { id: 328, section: "J", feature: "No raw camera archive", impl: "DONE", proof: "PA", batch: "—", owner: false },
  { id: 329, section: "J", feature: "Structured perception only", impl: "DONE", proof: "PA", batch: "—", owner: false },
  { id: 330, section: "J", feature: "Presence history", impl: "DONE", proof: "PA", batch: "B48", owner: false },
  { id: 331, section: "J", feature: "Ambient policy UI", impl: "PARTIAL", proof: "PA", batch: "B48", owner: false },
  { id: 332, section: "J", feature: "Auto display-off on/off", impl: "DONE", proof: "PA", batch: "B48", owner: false },
  { id: 333, section: "J", feature: "\"Uyurken ekranı kapat\"", impl: "DONE", proof: "PA", batch: "B48", owner: false },
  { id: 334, section: "J", feature: "\"Ben dönünce aç\"", impl: "DONE", proof: "PR", batch: "—", owner: false },
  { id: 335, section: "K", feature: "IMAP read", impl: "BLOCKED_PROVIDER", proof: "PA", batch: "B45", owner: false },
  { id: 336, section: "K", feature: "SMTP send", impl: "BLOCKED_PROVIDER", proof: "PA", batch: "B45", owner: false },
  { id: 337, section: "K", feature: "CalDAV read", impl: "BLOCKED_PROVIDER", proof: "PA", batch: "B46", owner: false },
  { id: 338, section: "K", feature: "Mail list", impl: "BLOCKED_PROVIDER", proof: "PA", batch: "B45", owner: false },
  { id: 339, section: "K", feature: "Mail search", impl: "BLOCKED_PROVIDER", proof: "PA", batch: "B45", owner: false },
  { id: 340, section: "K", feature: "Mail summarize", impl: "BLOCKED_PROVIDER", proof: "PA", batch: "B45", owner: false },
  { id: 341, section: "K", feature: "Thread summarize", impl: "BLOCKED_PROVIDER", proof: "PA", batch: "B45", owner: false },
  { id: 342, section: "K", feature: "Draft", impl: "BLOCKED_PROVIDER", proof: "PA", batch: "B45", owner: false },
  { id: 343, section: "K", feature: "Reply draft", impl: "DONE", proof: "PA", batch: "B45", owner: false },
  { id: 344, section: "K", feature: "Forward draft", impl: "BLOCKED_PROVIDER", proof: "PA", batch: "B45", owner: false },
  { id: 345, section: "K", feature: "Send confirmation gate", impl: "BLOCKED_PROVIDER", proof: "PA", batch: "B45", owner: false },
  { id: 346, section: "K", feature: "Reply References correctness", impl: "DONE", proof: "PA", batch: "B45", owner: false },
  { id: 347, section: "K", feature: "Attachment read", impl: "DONE", proof: "PA", batch: "B45", owner: false },
  { id: 348, section: "K", feature: "Attachment save", impl: "DONE", proof: "PA", batch: "B45", owner: false },
  { id: 349, section: "K", feature: "Calendar list", impl: "BLOCKED_PROVIDER", proof: "PA", batch: "B46", owner: false },
  { id: 350, section: "K", feature: "Calendar today", impl: "BLOCKED_PROVIDER", proof: "PA", batch: "B46", owner: false },
  { id: 351, section: "K", feature: "Calendar week", impl: "BLOCKED_PROVIDER", proof: "PA", batch: "B46", owner: false },
  { id: 352, section: "K", feature: "Create event proposal", impl: "BLOCKED_PROVIDER", proof: "PA", batch: "B46", owner: false },
  { id: 353, section: "K", feature: "Edit event proposal", impl: "BLOCKED_PROVIDER", proof: "PA", batch: "B46", owner: false },
  { id: 354, section: "K", feature: "Cancel event", impl: "DONE", proof: "PA", batch: "B46", owner: false },
  { id: 355, section: "K", feature: "RSVP", impl: "DEFERRED", proof: "NYP", batch: "B46", owner: false },
  { id: 356, section: "K", feature: "RRULE", impl: "DONE", proof: "PA", batch: "B46", owner: false },
  { id: 357, section: "K", feature: "VALARM", impl: "DONE", proof: "PA", batch: "B46", owner: false },
  { id: 358, section: "K", feature: "Reminder", impl: "DONE", proof: "PA", batch: "B46", owner: false },
  { id: 359, section: "K", feature: "Calendar index", impl: "DONE", proof: "PA", batch: "B46", owner: false },
  { id: 360, section: "K", feature: "Mail polling", impl: "DONE", proof: "PA", batch: "B45", owner: false },
  { id: 361, section: "K", feature: "Calendar sync", impl: "DONE", proof: "PA", batch: "B46", owner: false },
  { id: 362, section: "K", feature: "Morning mail summary", impl: "DONE", proof: "PA", batch: "B45", owner: false },
  { id: 363, section: "K", feature: "Morning calendar summary", impl: "DONE", proof: "PA", batch: "B46", owner: false },
  { id: 364, section: "K", feature: "\"Maillerime bak\"", impl: "DONE", proof: "PA", batch: "B45", owner: false },
  { id: 365, section: "K", feature: "\"Bu hafta ne var?\"", impl: "DONE", proof: "PA", batch: "B46", owner: false },
  { id: 366, section: "K", feature: "\"Perşembe toplantısını iptal et\"", impl: "DONE", proof: "PA", batch: "B46", owner: false },
  { id: 367, section: "L", feature: "Durable notification table", impl: "DONE", proof: "PA", batch: "B11", owner: false },
  { id: 368, section: "L", feature: "In-app inbox", impl: "DONE", proof: "PA", batch: "B11", owner: false },
  { id: 369, section: "L", feature: "Desktop toast", impl: "DONE", proof: "PA", batch: "B11", owner: true },
  { id: 370, section: "L", feature: "Toast action buttons", impl: "DONE", proof: "PA", batch: "B11", owner: true },
  { id: 371, section: "L", feature: "Device audio notification", impl: "DONE", proof: "PR", batch: "—", owner: false },
  { id: 372, section: "L", feature: "WebPush", impl: "BLOCKED_OWNER", proof: "BLK", batch: "B11", owner: false },
  { id: 373, section: "L", feature: "FCM", impl: "BLOCKED_PROVIDER", proof: "PU", batch: "B12", owner: false },
  { id: 374, section: "L", feature: "APNs", impl: "BLOCKED_PROVIDER", proof: "PU", batch: "B12", owner: false },
  { id: 375, section: "L", feature: "Delivery receipt", impl: "DONE", proof: "PA", batch: "B07", owner: false },
  { id: 376, section: "L", feature: "Delivery retry", impl: "DONE", proof: "PA", batch: "B07", owner: false },
  { id: 377, section: "L", feature: "Delivery history", impl: "DONE", proof: "PA", batch: "B11", owner: false },
  { id: 378, section: "L", feature: "Priority", impl: "DONE", proof: "PA", batch: "B11", owner: false },
  { id: 379, section: "L", feature: "Quiet hours", impl: "DONE", proof: "PA", batch: "B11", owner: false },
  { id: 380, section: "L", feature: "Notification grouping", impl: "DONE", proof: "PA", batch: "B11", owner: false },
  { id: 381, section: "L", feature: "\"Task completed\"", impl: "DONE", proof: "PA", batch: "B12", owner: false },
  { id: 382, section: "L", feature: "\"Task failed\"", impl: "DONE", proof: "PA", batch: "B12", owner: false },
  { id: 383, section: "L", feature: "\"Owner approval required\"", impl: "DONE", proof: "PA", batch: "B12", owner: false },
  { id: 384, section: "L", feature: "\"Rollback happened\"", impl: "DONE", proof: "PA", batch: "B12", owner: false },
  { id: 385, section: "L", feature: "\"Backup failed\"", impl: "DONE", proof: "PA", batch: "B12", owner: false },
  { id: 386, section: "L", feature: "\"Alarm failed\"", impl: "DONE", proof: "PA", batch: "B12", owner: false },
  { id: 387, section: "L", feature: "\"Research finished\"", impl: "DONE", proof: "PA", batch: "B12", owner: false },
  { id: 388, section: "L", feature: "\"SelfDev candidate ready\"", impl: "DONE", proof: "PA", batch: "B12", owner: false },
  { id: 389, section: "L", feature: "Notification fallback ladder", impl: "DONE", proof: "PA", batch: "B11", owner: false },
  { id: 390, section: "L", feature: "Fake provider must never report delivered", impl: "DONE", proof: "PA", batch: "B07", owner: false },
  { id: 391, section: "M", feature: "PDF", impl: "DONE", proof: "PR", batch: "—", owner: false },
  { id: 392, section: "M", feature: "DOCX", impl: "DONE", proof: "PR", batch: "—", owner: false },
  { id: 393, section: "M", feature: "XLSX", impl: "DONE", proof: "PA", batch: "B42", owner: false },
  { id: 394, section: "M", feature: "PPTX", impl: "DONE", proof: "PA", batch: "B42", owner: false },
  { id: 395, section: "M", feature: "HTML", impl: "DONE", proof: "PR", batch: "—", owner: false },
  { id: 396, section: "M", feature: "Markdown", impl: "DONE", proof: "PR", batch: "—", owner: false },
  { id: 397, section: "M", feature: "TXT", impl: "DONE", proof: "PR", batch: "—", owner: false },
  { id: 398, section: "M", feature: "CSV", impl: "DONE", proof: "PA", batch: "B42", owner: false },
  { id: 399, section: "M", feature: "JSON", impl: "DONE", proof: "PA", batch: "B42", owner: false },
  { id: 400, section: "M", feature: "Image artifact", impl: "DONE", proof: "PA", batch: "B42", owner: false },
  { id: 401, section: "M", feature: "Deterministic render", impl: "DONE", proof: "PA", batch: "—", owner: false },
  { id: 402, section: "M", feature: "Independent read-back", impl: "DONE", proof: "PA", batch: "—", owner: false },
  { id: 403, section: "M", feature: "Reopen validation", impl: "DONE", proof: "PA", batch: "—", owner: false },
  { id: 404, section: "M", feature: "Spreadsheet formula validation", impl: "DONE", proof: "PA", batch: "—", owner: false },
  { id: 405, section: "M", feature: "Provenance", impl: "DONE", proof: "PA", batch: "B42", owner: false },
  { id: 406, section: "M", feature: "Actor provenance", impl: "DONE", proof: "PA", batch: "B42", owner: false },
  { id: 407, section: "M", feature: "Library/runtime version provenance", impl: "DONE", proof: "PA", batch: "B42", owner: false },
  { id: 408, section: "M", feature: "Source manifest", impl: "DONE", proof: "PA", batch: "B42", owner: false },
  { id: 409, section: "M", feature: "Artifact versioning", impl: "DONE", proof: "PA", batch: "B42", owner: false },
  { id: 410, section: "M", feature: "Artifact edit", impl: "DONE", proof: "PA", batch: "B42", owner: false },
  { id: 411, section: "M", feature: "Artifact clone", impl: "DONE", proof: "PA", batch: "B42", owner: false },
  { id: 412, section: "M", feature: "Artifact delete policy", impl: "DONE", proof: "PA", batch: "B42", owner: false },
  { id: 413, section: "M", feature: "Export to owner disk", impl: "DONE", proof: "PR", batch: "—", owner: false },
  { id: 414, section: "M", feature: "Artifact narration", impl: "DONE", proof: "PA", batch: "B21", owner: false },
  { id: 415, section: "M", feature: "Artifact compare", impl: "DONE", proof: "PA", batch: "B42", owner: false },
  { id: 416, section: "M", feature: "Artifact diff", impl: "DONE", proof: "PA", batch: "B42", owner: false },
  { id: 417, section: "N", feature: "Fixed template generation", impl: "DONE", proof: "PA", batch: "B03", owner: false },
  { id: 418, section: "N", feature: "Task tracker", impl: "DONE", proof: "PA", batch: "B03", owner: false },
  { id: 419, section: "N", feature: "Static site", impl: "DONE", proof: "PA", batch: "B03", owner: false },
  { id: 420, section: "N", feature: "CLI tool", impl: "DONE", proof: "PA", batch: "B03", owner: false },
  { id: 421, section: "N", feature: "Template manifest contract", impl: "DONE", proof: "PA", batch: "B03", owner: false },
  { id: 422, section: "N", feature: "General requirements parser", impl: "DONE", proof: "PA", batch: "B40", owner: false },
  { id: 423, section: "N", feature: "Architecture planner", impl: "DONE", proof: "PA", batch: "B40", owner: false },
  { id: 424, section: "N", feature: "Project planner", impl: "DONE", proof: "PA", batch: "B40", owner: false },
  { id: 425, section: "N", feature: "Model-backed code generation", impl: "DONE", proof: "PA", batch: "B40", owner: false },
  { id: 426, section: "N", feature: "Multiple source files", impl: "DONE", proof: "PA", batch: "B40", owner: false },
  { id: 427, section: "N", feature: "Database generation", impl: "DONE", proof: "PA", batch: "B40", owner: false },
  { id: 428, section: "N", feature: "API generation", impl: "DONE", proof: "PA", batch: "B40", owner: false },
  { id: 429, section: "N", feature: "Frontend generation", impl: "DONE", proof: "PA", batch: "B40", owner: false },
  { id: 430, section: "N", feature: "Auth generation", impl: "DONE", proof: "PA", batch: "B40", owner: false },
  { id: 431, section: "N", feature: "Test generation", impl: "DONE", proof: "PA", batch: "B40", owner: false },
  { id: 432, section: "N", feature: "Unit tests", impl: "DONE", proof: "PA", batch: "B40", owner: false },
  { id: 433, section: "N", feature: "Integration tests", impl: "DONE", proof: "PA", batch: "B40", owner: false },
  { id: 434, section: "N", feature: "Browser tests", impl: "DONE", proof: "PA", batch: "B40", owner: false },
  { id: 435, section: "N", feature: "Failed test analysis", impl: "DONE", proof: "PA", batch: "B40", owner: false },
  { id: 436, section: "N", feature: "Automated bug fix", impl: "DONE", proof: "PA", batch: "B40", owner: false },
  { id: 437, section: "N", feature: "Retry loop", impl: "DONE", proof: "PA", batch: "B40", owner: false },
  { id: 438, section: "N", feature: "Lint", impl: "DONE", proof: "PA", batch: "B40", owner: false },
  { id: 439, section: "N", feature: "Security scan", impl: "DONE", proof: "PA", batch: "B40", owner: false },
  { id: 440, section: "N", feature: "Build", impl: "DONE", proof: "PA", batch: "B41", owner: false },
  { id: 441, section: "N", feature: "Package", impl: "DONE", proof: "PA", batch: "B41", owner: false },
  { id: 442, section: "N", feature: "Launch", impl: "DONE", proof: "PA", batch: "B41", owner: false },
  { id: 443, section: "N", feature: "UI verification", impl: "DONE", proof: "PA", batch: "B41", owner: false },
  { id: 444, section: "N", feature: "Persistence verification", impl: "DONE", proof: "PA", batch: "B41", owner: false },
  { id: 445, section: "N", feature: "Log read-back", impl: "DONE", proof: "PA", batch: "B41", owner: false },
  { id: 446, section: "N", feature: "Release artifact", impl: "DONE", proof: "PA", batch: "B41", owner: false },
  { id: 447, section: "N", feature: "Project history", impl: "DONE", proof: "PA", batch: "B41", owner: false },
  { id: 448, section: "N", feature: "Resume development later", impl: "DONE", proof: "PA", batch: "B41", owner: false },
  { id: 449, section: "N", feature: "Modify existing generated app", impl: "DONE", proof: "PA", batch: "B41", owner: false },
  { id: 450, section: "N", feature: "\"Bu uygulamaya şu özelliği ekle\"", impl: "DONE", proof: "PA", batch: "B41", owner: false },
  { id: 451, section: "N", feature: "\"Bu bug'ı düzelt\"", impl: "DONE", proof: "PA", batch: "B41", owner: false },
  { id: 452, section: "N", feature: "Arbitrary bounded app request", impl: "DONE", proof: "PA", batch: "B41", owner: false },
  { id: 453, section: "O", feature: "NativeAppSpec", impl: "DONE", proof: "PA", batch: "—", owner: false },
  { id: 454, section: "O", feature: "WPF generation", impl: "DONE", proof: "PR", batch: "—", owner: false },
  { id: 455, section: "O", feature: "EXE", impl: "DONE", proof: "PR", batch: "—", owner: false },
  { id: 456, section: "O", feature: "Portable ZIP", impl: "DONE", proof: "PA", batch: "B33", owner: false },
  { id: 457, section: "O", feature: "MSIX", impl: "DONE", proof: "PA", batch: "B33", owner: false },
  { id: 458, section: "O", feature: "PE validation", impl: "DONE", proof: "PA", batch: "—", owner: false },
  { id: 459, section: "O", feature: "Build identity", impl: "DONE", proof: "PR", batch: "—", owner: false },
  { id: 460, section: "O", feature: "Device build", impl: "DONE", proof: "PR", batch: "—", owner: false },
  { id: 461, section: "O", feature: "Cloud-triggered device build", impl: "DONE", proof: "PR", batch: "—", owner: false },
  { id: 462, section: "O", feature: "App launch", impl: "DONE", proof: "PA", batch: "B33", owner: false },
  { id: 463, section: "O", feature: "UI Automation", impl: "DONE", proof: "PA", batch: "B33", owner: false },
  { id: 464, section: "O", feature: "Relaunch", impl: "DONE", proof: "PA", batch: "B33", owner: false },
  { id: 465, section: "O", feature: "Persistence", impl: "DONE", proof: "PA", batch: "B33", owner: false },
  { id: 466, section: "O", feature: "App log", impl: "DONE", proof: "PA", batch: "B33", owner: false },
  { id: 467, section: "O", feature: "Test count parsing", impl: "DONE", proof: "PA", batch: "B03", owner: false },
  { id: 468, section: "O", feature: "Native install", impl: "DONE", proof: "PA", batch: "B33", owner: false },
  { id: 469, section: "O", feature: "Native uninstall", impl: "DONE", proof: "PA", batch: "B33", owner: false },
  { id: 470, section: "O", feature: "Native fix", impl: "DONE", proof: "PA", batch: "B33", owner: false },
  { id: 471, section: "O", feature: "Native update", impl: "DONE", proof: "PA", batch: "B33", owner: false },
  { id: 472, section: "O", feature: "Signing policy", impl: "DONE", proof: "PA", batch: "B33", owner: false },
  { id: 473, section: "O", feature: "Signing optional/test cert", impl: "DONE", proof: "PA", batch: "B33", owner: false },
  { id: 474, section: "O", feature: "Android project generation", impl: "DONE", proof: "PA", batch: "B49", owner: false },
  { id: 475, section: "O", feature: "APK", impl: "PARTIAL", proof: "PR", batch: "B49", owner: false },
  { id: 476, section: "O", feature: "AAB", impl: "PARTIAL", proof: "PR", batch: "B49", owner: false },
  { id: 477, section: "O", feature: "Android emulator test", impl: "PARTIAL", proof: "PR", batch: "B49", owner: false },
  { id: 478, section: "O", feature: "Android device test", impl: "BLOCKED_PROVIDER", proof: "NYP", batch: "B49", owner: false },
  { id: 479, section: "O", feature: "iOS explicit NOT_SUPPORTED without macOS", impl: "DONE", proof: "PA", batch: "B49", owner: false },
  { id: 480, section: "O", feature: "Generated app auto-update later", impl: "DEFERRED", proof: "NYP", batch: "B41", owner: false },
  { id: 481, section: "P", feature: "Pillow raster edits", impl: "DONE", proof: "PA", batch: "—", owner: false },
  { id: 482, section: "P", feature: "Crop", impl: "DONE", proof: "PA", batch: "—", owner: false },
  { id: 483, section: "P", feature: "Resize", impl: "DONE", proof: "PA", batch: "—", owner: false },
  { id: 484, section: "P", feature: "Rotate", impl: "DONE", proof: "PA", batch: "—", owner: false },
  { id: 485, section: "P", feature: "Draw", impl: "DONE", proof: "PA", batch: "—", owner: false },
  { id: 486, section: "P", feature: "Text", impl: "DONE", proof: "PA", batch: "—", owner: false },
  { id: 487, section: "P", feature: "Shapes", impl: "DONE", proof: "PA", batch: "—", owner: false },
  { id: 488, section: "P", feature: "Composite", impl: "DONE", proof: "PA", batch: "—", owner: false },
  { id: 489, section: "P", feature: "Background removal", impl: "DONE", proof: "PA", batch: "B43", owner: false },
  { id: 490, section: "P", feature: "Object removal", impl: "DONE", proof: "PA", batch: "B43", owner: false },
  { id: 491, section: "P", feature: "Object addition", impl: "DONE", proof: "PA", batch: "B43", owner: false },
  { id: 492, section: "P", feature: "Image generation", impl: "DONE", proof: "PA", batch: "B43", owner: false },
  { id: 493, section: "P", feature: "Image style transformation", impl: "DONE", proof: "PA", batch: "B43", owner: false },
  { id: 494, section: "P", feature: "Image enhancement", impl: "DONE", proof: "PA", batch: "B43", owner: false },
  { id: 495, section: "P", feature: "Upscale", impl: "DONE", proof: "PA", batch: "B43", owner: false },
  { id: 496, section: "P", feature: "OCR", impl: "DONE", proof: "PA", batch: "B32", owner: false },
  { id: 497, section: "P", feature: "Independent pixel validation", impl: "DONE", proof: "PA", batch: "—", owner: false },
  { id: 498, section: "P", feature: "Visual semantic validation", impl: "DONE", proof: "PA", batch: "B43", owner: false },
  { id: 499, section: "P", feature: "Paint open/display", impl: "DONE", proof: "PA", batch: "—", owner: false },
  { id: 500, section: "P", feature: "Paint real UI operation", impl: "DONE", proof: "PA", batch: "B43", owner: false },
  { id: 501, section: "P", feature: "Photoshop detection", impl: "DONE", proof: "PA", batch: "—", owner: false },
  { id: 502, section: "P", feature: "Photoshop driver", impl: "DONE", proof: "PA", batch: "B43", owner: false },
  { id: 503, section: "P", feature: "Illustrator detection", impl: "DONE", proof: "PA", batch: "—", owner: false },
  { id: 504, section: "P", feature: "Illustrator driver", impl: "DONE", proof: "PA", batch: "B43", owner: false },
  { id: 505, section: "P", feature: "Figma integration", impl: "DONE", proof: "PA", batch: "B03", owner: false },
  { id: 506, section: "P", feature: "Layer-aware editing", impl: "DONE", proof: "PA", batch: "B43", owner: false },
  { id: 507, section: "P", feature: "PSD support", impl: "DONE", proof: "PA", batch: "B43", owner: false },
  { id: 508, section: "P", feature: "SVG support", impl: "DONE", proof: "PA", batch: "B43", owner: false },
  { id: 509, section: "P", feature: "Export to owner disk", impl: "DONE", proof: "PA", batch: "B43", owner: false },
  { id: 510, section: "P", feature: "Creative history", impl: "DONE", proof: "PA", batch: "B03", owner: false },
  { id: 511, section: "P", feature: "Undo/redo", impl: "DONE", proof: "PA", batch: "B43", owner: false },
  { id: 512, section: "P", feature: "\"Bu fotoğrafı düzelt\"", impl: "DONE", proof: "PA", batch: "B43", owner: false },
  { id: 513, section: "Q", feature: "Blender detection", impl: "DONE", proof: "PR", batch: "—", owner: false },
  { id: 514, section: "Q", feature: "Blender structured scene", impl: "DONE", proof: "PA", batch: "—", owner: false },
  { id: 515, section: "Q", feature: "Scene plan JSON", impl: "DONE", proof: "PA", batch: "—", owner: false },
  { id: 516, section: "Q", feature: "Blender Python driver", impl: "DONE", proof: "PR", batch: "—", owner: false },
  { id: 517, section: "Q", feature: "Save .blend", impl: "DONE", proof: "PR", batch: "—", owner: false },
  { id: 518, section: "Q", feature: "Render", impl: "DONE", proof: "PR", batch: "—", owner: false },
  { id: 519, section: "Q", feature: "Independent render verify", impl: "DONE", proof: "PA", batch: "—", owner: false },
  { id: 520, section: "Q", feature: "Scene inspect", impl: "DONE", proof: "PA", batch: "B44", owner: false },
  { id: 521, section: "Q", feature: "Production scene creation", impl: "DONE", proof: "PA", batch: "B44", owner: false },
  { id: 522, section: "Q", feature: "Modify existing scene", impl: "DONE", proof: "PA", batch: "B44", owner: false },
  { id: 523, section: "Q", feature: "Material control", impl: "DONE", proof: "PA", batch: "B44", owner: false },
  { id: 524, section: "Q", feature: "Lighting control", impl: "DONE", proof: "PA", batch: "B44", owner: false },
  { id: 525, section: "Q", feature: "Camera control", impl: "DONE", proof: "PA", batch: "B44", owner: false },
  { id: 526, section: "Q", feature: "Animation", impl: "DONE", proof: "PA", batch: "B44", owner: false },
  { id: 527, section: "Q", feature: "Export FBX/GLTF", impl: "DONE", proof: "PA", batch: "B44", owner: false },
  { id: 528, section: "Q", feature: "Unity detection", impl: "DONE", proof: "PA", batch: "—", owner: false },
  { id: 529, section: "Q", feature: "Unity licensing state", impl: "DONE", proof: "PA", batch: "—", owner: false },
  { id: 530, section: "Q", feature: "Unity project create", impl: "DONE", proof: "PR", batch: "B50", owner: false },
  { id: 531, section: "Q", feature: "Unity scene create", impl: "DONE", proof: "PR", batch: "B50", owner: false },
  { id: 532, section: "Q", feature: "Unity build", impl: "DONE", proof: "PR", batch: "B50", owner: false },
  { id: 533, section: "Q", feature: "Unity test", impl: "DONE", proof: "PR", batch: "B50", owner: false },
  { id: 534, section: "Q", feature: "Unreal later/optional", impl: "DEFERRED", proof: "NYP", batch: "B50", owner: false },
  { id: 535, section: "R", feature: "Durable task graph", impl: "DONE", proof: "PR", batch: "—", owner: false },
  { id: 536, section: "R", feature: "Step preconditions", impl: "DONE", proof: "PA", batch: "B38", owner: false },
  { id: 537, section: "R", feature: "Step postconditions", impl: "DONE", proof: "PA", batch: "B38", owner: false },
  { id: 538, section: "R", feature: "Retry", impl: "DONE", proof: "PA", batch: "B38", owner: false },
  { id: 539, section: "R", feature: "Compensation", impl: "DONE", proof: "PA", batch: "B10", owner: false },
  { id: 540, section: "R", feature: "Pause", impl: "DONE", proof: "PA", batch: "—", owner: false },
  { id: 541, section: "R", feature: "Resume", impl: "DONE", proof: "PA", batch: "—", owner: false },
  { id: 542, section: "R", feature: "Cancel", impl: "DONE", proof: "PA", batch: "—", owner: false },
  { id: 543, section: "R", feature: "Modify", impl: "DONE", proof: "PA", batch: "—", owner: false },
  { id: 544, section: "R", feature: "Human approval step", impl: "DONE", proof: "PA", batch: "B38", owner: false },
  { id: 545, section: "R", feature: "Task history", impl: "DONE", proof: "PA", batch: "—", owner: false },
  { id: 546, section: "R", feature: "Task explanation", impl: "DONE", proof: "PA", batch: "B38", owner: false },
  { id: 547, section: "R", feature: "Research-report plan", impl: "DONE", proof: "PR", batch: "—", owner: false },
  { id: 548, section: "R", feature: "Folder-compare plan", impl: "DONE", proof: "PA", batch: "B10", owner: false },
  { id: 549, section: "R", feature: "Mail-sequence plan", impl: "BLOCKED_PROVIDER", proof: "PU", batch: "B38", owner: false },
  { id: 550, section: "R", feature: "General model planner", impl: "DONE", proof: "PA", batch: "B38", owner: false },
  { id: 551, section: "R", feature: "Dynamic plan generation", impl: "DONE", proof: "PA", batch: "B38", owner: false },
  { id: 552, section: "R", feature: "Dynamic step selection", impl: "DONE", proof: "PA", batch: "B38", owner: false },
  { id: 553, section: "R", feature: "Parallel steps", impl: "DONE", proof: "PA", batch: "B38", owner: false },
  { id: 554, section: "R", feature: "Conditional branches", impl: "DONE", proof: "PA", batch: "B38", owner: false },
  { id: 555, section: "R", feature: "Loop steps", impl: "DONE", proof: "PA", batch: "B38", owner: false },
  { id: 556, section: "R", feature: "Timeout policy", impl: "DONE", proof: "PA", batch: "B38", owner: false },
  { id: 557, section: "R", feature: "Recovery from partial failure", impl: "DONE", proof: "PA", batch: "B38", owner: false },
  { id: 558, section: "R", feature: "Correct final status", impl: "DONE", proof: "PA", batch: "B10", owner: false },
  { id: 559, section: "R", feature: "No false \"4/4 completed\"", impl: "DONE", proof: "PA", batch: "B10", owner: false },
  { id: 560, section: "R", feature: "Task reconciliation", impl: "DONE", proof: "PA", batch: "B10", owner: false },
  { id: 561, section: "S", feature: "Capability request", impl: "DONE", proof: "PA", batch: "B36", owner: false },
  { id: 562, section: "S", feature: "Catalogue", impl: "DONE", proof: "PA", batch: "B36", owner: false },
  { id: 563, section: "S", feature: "Catalogue registration", impl: "DONE", proof: "PA", batch: "B36", owner: false },
  { id: 564, section: "S", feature: "Discovery", impl: "DONE", proof: "PA", batch: "B36", owner: false },
  { id: 565, section: "S", feature: "Interface inspection", impl: "DONE", proof: "PA", batch: "B36", owner: false },
  { id: 566, section: "S", feature: "Adapter generation", impl: "DONE", proof: "PA", batch: "—", owner: false },
  { id: 567, section: "S", feature: "Adapter tests", impl: "DONE", proof: "PA", batch: "—", owner: false },
  { id: 568, section: "S", feature: "Sandbox", impl: "DONE", proof: "PA", batch: "—", owner: false },
  { id: 569, section: "S", feature: "Registration", impl: "DONE", proof: "PA", batch: "B36", owner: false },
  { id: 570, section: "S", feature: "Activation", impl: "DONE", proof: "PA", batch: "B36", owner: false },
  { id: 571, section: "S", feature: "Versioning", impl: "DONE", proof: "PA", batch: "B36", owner: false },
  { id: 572, section: "S", feature: "Rollback", impl: "DONE", proof: "PA", batch: "B36", owner: false },
  { id: 573, section: "S", feature: "Production capability use", impl: "DONE", proof: "PA", batch: "B36", owner: false },
  { id: 574, section: "S", feature: "Genesis REST", impl: "DONE", proof: "PA", batch: "B36", owner: false },
  { id: 575, section: "S", feature: "Genesis Voice tool", impl: "DONE", proof: "PA", batch: "B36", owner: false },
  { id: 576, section: "S", feature: "Genesis Cockpit UI", impl: "DONE", proof: "PA", batch: "B36", owner: false },
  { id: 577, section: "S", feature: "Model-backed capability generation", impl: "DONE", proof: "PA", batch: "B36", owner: false },
  { id: 578, section: "S", feature: "Restricted app-only generation", impl: "DONE", proof: "PA", batch: "B36", owner: false },
  { id: 579, section: "S", feature: "Security gate", impl: "DONE", proof: "PA", batch: "B36", owner: false },
  { id: 580, section: "S", feature: "Owner approval", impl: "DONE", proof: "PA", batch: "B36", owner: false },
  { id: 581, section: "T", feature: "Defect intake", impl: "DONE", proof: "PA", batch: "B35", owner: false },
  { id: 582, section: "T", feature: "Opportunity intake", impl: "DONE", proof: "PR", batch: "—", owner: false },
  { id: 583, section: "T", feature: "Opportunity to defect bridge", impl: "DONE", proof: "PA", batch: "B35", owner: false },
  { id: 584, section: "T", feature: "Risk classification", impl: "DONE", proof: "PA", batch: "—", owner: false },
  { id: 585, section: "T", feature: "Promotion class", impl: "DONE", proof: "PA", batch: "B35", owner: false },
  { id: 586, section: "T", feature: "Real git branch", impl: "DONE", proof: "PR", batch: "—", owner: false },
  { id: 587, section: "T", feature: "Real git worktree", impl: "DONE", proof: "PR", batch: "—", owner: false },
  { id: 588, section: "T", feature: "Codebase analysis", impl: "DONE", proof: "PA", batch: "—", owner: false },
  { id: 589, section: "T", feature: "Architecture planning", impl: "DONE", proof: "PA", batch: "B35", owner: false },
  { id: 590, section: "T", feature: "Patch generation", impl: "DONE", proof: "PR", batch: "—", owner: false },
  { id: 591, section: "T", feature: "New module generation", impl: "DONE", proof: "PA", batch: "—", owner: false },
  { id: 592, section: "T", feature: "Regression test generation", impl: "DONE", proof: "PA", batch: "—", owner: false },
  { id: 593, section: "T", feature: "Targeted tests", impl: "DONE", proof: "PR", batch: "—", owner: false },
  { id: 594, section: "T", feature: "Failure analysis", impl: "DONE", proof: "PR", batch: "—", owner: false },
  { id: 595, section: "T", feature: "Automated fix", impl: "DONE", proof: "PR", batch: "—", owner: false },
  { id: 596, section: "T", feature: "Retry", impl: "DONE", proof: "PA", batch: "—", owner: false },
  { id: 597, section: "T", feature: "Static review", impl: "DONE", proof: "PA", batch: "—", owner: false },
  { id: 598, section: "T", feature: "Security review", impl: "DONE", proof: "PA", batch: "B35", owner: false },
  { id: 599, section: "T", feature: "General code review", impl: "DONE", proof: "PA", batch: "—", owner: false },
  { id: 600, section: "T", feature: "Full quality gate", impl: "DONE", proof: "PA", batch: "B35", owner: false },
  { id: 601, section: "T", feature: "CI trigger", impl: "DONE", proof: "PA", batch: "B35", owner: false },
  { id: 602, section: "T", feature: "CI result read", impl: "DONE", proof: "PR", batch: "—", owner: false },
  { id: 603, section: "T", feature: "CI failure to code fix loop", impl: "DONE", proof: "PA", batch: "B35", owner: false },
  { id: 604, section: "T", feature: "Candidate commit", impl: "DONE", proof: "PR", batch: "—", owner: false },
  { id: 605, section: "T", feature: "Candidate evidence", impl: "DONE", proof: "PR", batch: "—", owner: false },
  { id: 606, section: "T", feature: "Candidate history", impl: "DONE", proof: "PR", batch: "—", owner: false },
  { id: 607, section: "T", feature: "Candidate quarantine", impl: "DONE", proof: "PA", batch: "—", owner: false },
  { id: 608, section: "T", feature: "Candidate shadow", impl: "DONE", proof: "PA", batch: "B35", owner: false },
  { id: 609, section: "T", feature: "Owner approval", impl: "DONE", proof: "PA", batch: "B35", owner: false },
  { id: 610, section: "T", feature: "Blue/green release", impl: "DONE", proof: "PR", batch: "—", owner: false },
  { id: 611, section: "T", feature: "Rollback", impl: "DONE", proof: "PR", batch: "—", owner: false },
  { id: 612, section: "T", feature: "Last-known-good", impl: "DONE", proof: "PR", batch: "—", owner: false },
  { id: 613, section: "T", feature: "Post-release health", impl: "DONE", proof: "PR", batch: "—", owner: false },
  { id: 614, section: "T", feature: "Post-release rollback", impl: "PARTIAL", proof: "PA", batch: "B08", owner: false },
  { id: 615, section: "T", feature: "Scheduler", impl: "DONE", proof: "PA", batch: "B35", owner: false },
  { id: 616, section: "T", feature: "Attempt budget", impl: "DONE", proof: "PA", batch: "—", owner: false },
  { id: 617, section: "T", feature: "Time budget", impl: "DONE", proof: "PA", batch: "—", owner: false },
  { id: 618, section: "T", feature: "Token/model budget", impl: "DONE", proof: "PA", batch: "B35", owner: false },
  { id: 619, section: "T", feature: "Disk budget", impl: "DONE", proof: "PA", batch: "B35", owner: false },
  { id: 620, section: "T", feature: "Parallel candidate limit", impl: "DONE", proof: "PA", batch: "B35", owner: false },
  { id: 621, section: "T", feature: "SelfDev Cockpit", impl: "DONE", proof: "PA", batch: "B35", owner: false },
  { id: 622, section: "T", feature: "\"Şu bug'ı kendin düzelt\"", impl: "DONE", proof: "PA", batch: "B35", owner: false },
  { id: 623, section: "T", feature: "\"Şu özelliği kendine ekle\"", impl: "DONE", proof: "PA", batch: "B35", owner: false },
  { id: 624, section: "T", feature: "No autonomous high-risk promotion", impl: "DONE", proof: "PA", batch: "—", owner: false },
  { id: 625, section: "T", feature: "Low-risk AUTO_SAFE option later", impl: "DEFERRED", proof: "NYP", batch: "—", owner: false },
  { id: 626, section: "U", feature: "PostgreSQL backup", impl: "DONE", proof: "PR", batch: "—", owner: false },
  { id: 627, section: "U", feature: "PostgreSQL role backup", impl: "DONE", proof: "PR", batch: "—", owner: false },
  { id: 628, section: "U", feature: "MinIO backup", impl: "DONE", proof: "PR", batch: "—", owner: false },
  { id: 629, section: "U", feature: "Config backup", impl: "DONE", proof: "PR", batch: "—", owner: false },
  { id: 630, section: "U", feature: "Identity-root backup strategy", impl: "DONE", proof: "PR", batch: "B09", owner: false },
  { id: 631, section: "U", feature: "Release metadata", impl: "DONE", proof: "PR", batch: "B01", owner: false },
  { id: 632, section: "U", feature: "Recovery metadata", impl: "DONE", proof: "PA", batch: "B01", owner: false },
  { id: 633, section: "U", feature: "Encryption", impl: "DONE", proof: "PR", batch: "—", owner: false },
  { id: 634, section: "U", feature: "Integrity hash", impl: "DONE", proof: "PR", batch: "—", owner: false },
  { id: 635, section: "U", feature: "Retention", impl: "DONE", proof: "PA", batch: "—", owner: false },
  { id: 636, section: "U", feature: "Daily schedule", impl: "DONE", proof: "PR", batch: "—", owner: false },
  { id: 637, section: "U", feature: "Weekly restore drill", impl: "DONE", proof: "PR", batch: "—", owner: false },
  { id: 638, section: "U", feature: "Pre-migration backup", impl: "DONE", proof: "PA", batch: "—", owner: false },
  { id: 639, section: "U", feature: "Restore script", impl: "DONE", proof: "PR", batch: "—", owner: false },
  { id: 640, section: "U", feature: "PostgreSQL restore", impl: "DONE", proof: "PR", batch: "—", owner: false },
  { id: 641, section: "U", feature: "MinIO restore", impl: "DONE", proof: "PR", batch: "—", owner: false },
  { id: 642, section: "U", feature: "Config restore", impl: "DONE", proof: "PA", batch: "B09", owner: false },
  { id: 643, section: "U", feature: "Release restore", impl: "DONE", proof: "PA", batch: "B09", owner: false },
  { id: 644, section: "U", feature: "Off-host repository", impl: "DONE", proof: "PA", batch: "B09", owner: false },
  { id: 645, section: "U", feature: "S3-compatible target", impl: "BLOCKED_OWNER", proof: "BLK", batch: "B09", owner: false },
  { id: 646, section: "U", feature: "Backup health", impl: "DONE", proof: "PA", batch: "B08", owner: false },
  { id: 647, section: "U", feature: "Backup failure notification", impl: "DONE", proof: "PA", batch: "B08", owner: false },
  { id: 648, section: "U", feature: "Restore health", impl: "DONE", proof: "PA", batch: "B08", owner: false },
  { id: 649, section: "U", feature: "RPO measurement", impl: "DONE", proof: "PA", batch: "B08", owner: false },
  { id: 650, section: "U", feature: "RTO measurement", impl: "DONE", proof: "PA", batch: "B08", owner: false },
  { id: 651, section: "U", feature: "Recovery supervisor", impl: "PARTIAL", proof: "PA", batch: "B08", owner: false },
  { id: 652, section: "U", feature: "Recovery systemd timer", impl: "PARTIAL", proof: "PA", batch: "B08", owner: false },
  { id: 653, section: "U", feature: "Healthy to degraded detection", impl: "PARTIAL", proof: "PA", batch: "B08", owner: false },
  { id: 654, section: "U", feature: "Automatic rollback", impl: "PARTIAL", proof: "PA", batch: "B08", owner: false },
  { id: 655, section: "U", feature: "Recovery audit", impl: "PARTIAL", proof: "PA", batch: "B08", owner: false },
  { id: 656, section: "V", feature: "Owner credential", impl: "DONE", proof: "PR", batch: "—", owner: false },
  { id: 657, section: "V", feature: "Session authentication", impl: "DONE", proof: "PA", batch: "—", owner: false },
  { id: 658, section: "V", feature: "Absolute session lifetime", impl: "DONE", proof: "PA", batch: "B05", owner: false },
  { id: 659, section: "V", feature: "Idle session lifetime", impl: "DONE", proof: "PA", batch: "B05", owner: false },
  { id: 660, section: "V", feature: "Panic revoke", impl: "DONE", proof: "PA", batch: "B25", owner: false },
  { id: 661, section: "V", feature: "Device enrollment", impl: "DONE", proof: "PR", batch: "—", owner: false },
  { id: 662, section: "V", feature: "Device revoke", impl: "DONE", proof: "PA", batch: "—", owner: false },
  { id: 663, section: "V", feature: "Device trust", impl: "DONE", proof: "PA", batch: "B05", owner: false },
  { id: 664, section: "V", feature: "Speaker verification", impl: "PARTIAL", proof: "PA", batch: "B05", owner: false },
  { id: 665, section: "V", feature: "Speaker embedding", impl: "PARTIAL", proof: "PA", batch: "B05", owner: false },
  { id: 666, section: "V", feature: "Sensitive-operation re-auth", impl: "PARTIAL", proof: "PA", batch: "B05", owner: false },
  { id: 667, section: "V", feature: "Secret detection", impl: "DONE", proof: "PA", batch: "—", owner: false },
  { id: 668, section: "V", feature: "Secret redaction", impl: "DONE", proof: "PA", batch: "B04", owner: false },
  { id: 669, section: "V", feature: "DPAPI storage", impl: "DONE", proof: "PR", batch: "—", owner: false },
  { id: 670, section: "V", feature: "Cloud credential separation", impl: "DONE", proof: "PA", batch: "—", owner: false },
  { id: 671, section: "V", feature: "Camera permission", impl: "DONE", proof: "PA", batch: "B48", owner: false },
  { id: 672, section: "V", feature: "Browser permission", impl: "DONE", proof: "PA", batch: "—", owner: false },
  { id: 673, section: "V", feature: "Research permission", impl: "DONE", proof: "PA", batch: "—", owner: false },
  { id: 674, section: "V", feature: "File mutation permission", impl: "DONE", proof: "PA", batch: "B34", owner: false },
  { id: 675, section: "V", feature: "Code promotion permission", impl: "DONE", proof: "PA", batch: "B05", owner: false },
  { id: 676, section: "V", feature: "Production deployment permission", impl: "DONE", proof: "PA", batch: "—", owner: false },
  { id: 677, section: "V", feature: "High-risk owner gate", impl: "DONE", proof: "PA", batch: "—", owner: false },
  { id: 678, section: "V", feature: "Permanent delete owner gate", impl: "DONE", proof: "PA", batch: "B05", owner: false },
  { id: 679, section: "V", feature: "Security audit ledger", impl: "DONE", proof: "PA", batch: "B07", owner: false },
  { id: 680, section: "V", feature: "Security review of generated code", impl: "DONE", proof: "PA", batch: "B35", owner: false },
  { id: 681, section: "V", feature: "No CAPTCHA bypass", impl: "DONE", proof: "PA", batch: "—", owner: false },
  { id: 682, section: "V", feature: "No DRM bypass", impl: "DONE", proof: "PA", batch: "—", owner: false },
  { id: 683, section: "V", feature: "No secret logging", impl: "DONE", proof: "PA", batch: "B04", owner: false },
  { id: 684, section: "V", feature: "No hidden camera", impl: "DONE", proof: "PA", batch: "—", owner: false },
  { id: 685, section: "W", feature: "Global navigation", impl: "DONE", proof: "PA", batch: "B23", owner: false },
  { id: 686, section: "W", feature: "Home dashboard", impl: "DONE", proof: "PA", batch: "B23", owner: false },
  { id: 687, section: "W", feature: "Voice page", impl: "DONE", proof: "PR", batch: "—", owner: false },
  { id: 688, section: "W", feature: "Core page", impl: "DONE", proof: "PR", batch: "—", owner: false },
  { id: 689, section: "W", feature: "Memory page", impl: "DONE", proof: "PA", batch: "B24", owner: false },
  { id: 690, section: "W", feature: "Tasks page", impl: "DONE", proof: "PA", batch: "B23", owner: false },
  { id: 691, section: "W", feature: "Research page", impl: "DONE", proof: "PA", batch: "B23", owner: false },
  { id: 692, section: "W", feature: "Artifacts page", impl: "DONE", proof: "PA", batch: "B23", owner: false },
  { id: 693, section: "W", feature: "Routines page", impl: "DONE", proof: "PA", batch: "B24", owner: false },
  { id: 694, section: "W", feature: "Alarm page", impl: "DONE", proof: "PA", batch: "B24", owner: false },
  { id: 695, section: "W", feature: "Device page", impl: "DONE", proof: "PA", batch: "B23", owner: false },
  { id: 696, section: "W", feature: "Security page", impl: "DONE", proof: "PA", batch: "B24", owner: false },
  { id: 697, section: "W", feature: "SelfDev page", impl: "DONE", proof: "PA", batch: "B24", owner: false },
  { id: 698, section: "W", feature: "Notifications page", impl: "DONE", proof: "PA", batch: "B24", owner: false },
  { id: 699, section: "W", feature: "Settings page", impl: "DONE", proof: "PA", batch: "B24", owner: false },
  { id: 700, section: "W", feature: "Feature availability page", impl: "DONE", proof: "PA", batch: "B24", owner: false },
  { id: 701, section: "W", feature: "\"Neler yapabilirsin?\"", impl: "DONE", proof: "PA", batch: "B25", owner: false },
  { id: 702, section: "W", feature: "Search", impl: "DONE", proof: "PA", batch: "B25", owner: false },
  { id: 703, section: "W", feature: "Global command palette", impl: "DONE", proof: "PA", batch: "B25", owner: false },
  { id: 704, section: "W", feature: "Turkish error dictionary", impl: "DONE", proof: "PA", batch: "B22", owner: false },
  { id: 705, section: "W", feature: "No Python errors shown", impl: "DONE", proof: "PA", batch: "B22", owner: false },
  { id: 706, section: "W", feature: "Empty-state UX", impl: "DONE", proof: "PA", batch: "B22", owner: false },
  { id: 707, section: "W", feature: "Loading state", impl: "DONE", proof: "PA", batch: "B22", owner: false },
  { id: 708, section: "W", feature: "Retry state", impl: "DONE", proof: "PA", batch: "B22", owner: false },
  { id: 709, section: "W", feature: "Provider-blocked state", impl: "DONE", proof: "PA", batch: "B22", owner: false },
  { id: 710, section: "W", feature: "Permission-required state", impl: "DONE", proof: "PA", batch: "B22", owner: false },
  { id: 711, section: "W", feature: "Owner-action-required state", impl: "DONE", proof: "PA", batch: "B22", owner: false },
  { id: 712, section: "W", feature: "Feature status badges", impl: "DONE", proof: "PA", batch: "B24", owner: false },
  { id: 713, section: "W", feature: "PROVEN_REAL badges", impl: "DONE", proof: "PA", batch: "B24", owner: false },
  { id: 714, section: "W", feature: "Cockpit panel cleanup", impl: "DONE", proof: "PA", batch: "B24", owner: false },
  { id: 715, section: "W", feature: "Broken /creative/runs route fix", impl: "DONE", proof: "PA", batch: "B03", owner: false },
  { id: 716, section: "W", feature: "PWA navigation", impl: "DONE", proof: "PA", batch: "B23", owner: false },
  { id: 717, section: "W", feature: "Dark fullscreen Living Core", impl: "DONE", proof: "PR", batch: "—", owner: false },
  { id: 718, section: "W", feature: "Gold/amber visual identity", impl: "DONE", proof: "PA", batch: "—", owner: false },
  { id: 719, section: "W", feature: "State-driven animation", impl: "DONE", proof: "PA", batch: "—", owner: false },
  { id: 720, section: "W", feature: "Minimal mode", impl: "DONE", proof: "PA", batch: "B23", owner: false },
  { id: 721, section: "W", feature: "Cockpit mode", impl: "DONE", proof: "PA", batch: "—", owner: false },
  { id: 722, section: "W", feature: "Performance levels", impl: "DONE", proof: "PA", batch: "B23", owner: false },
  { id: 723, section: "W", feature: "WebGL fallback", impl: "DONE", proof: "PA", batch: "B23", owner: false },
  { id: 724, section: "W", feature: "Accessibility", impl: "DONE", proof: "PA", batch: "B25", owner: false },
  { id: 725, section: "W", feature: "Keyboard navigation", impl: "DONE", proof: "PA", batch: "B25", owner: false },
  { id: 726, section: "X", feature: "\"Saat kaç?\"", impl: "DONE", proof: "PA", batch: "B27", owner: false },
  { id: 727, section: "X", feature: "\"Bunu hatırla\"", impl: "DONE", proof: "PA", batch: "B27", owner: false },
  { id: 728, section: "X", feature: "\"Bunu unut\"", impl: "DONE", proof: "PA", batch: "B27", owner: false },
  { id: 729, section: "X", feature: "\"Maillerime bak\"", impl: "DONE", proof: "PA", batch: "B27", owner: false },
  { id: 730, section: "X", feature: "\"Bu hafta ne var\"", impl: "DONE", proof: "PA", batch: "B27", owner: false },
  { id: 731, section: "X", feature: "\"Toplantıyı iptal et\"", impl: "DONE", proof: "PA", batch: "B27", owner: false },
  { id: 732, section: "X", feature: "\"Araştırmayı iptal et\"", impl: "DONE", proof: "PA", batch: "B27", owner: false },
  { id: 733, section: "X", feature: "\"Sesini kıs\"", impl: "DONE", proof: "PA", batch: "B27", owner: false },
  { id: 734, section: "X", feature: "\"Neler yapabilirsin\"", impl: "DONE", proof: "PA", batch: "B27", owner: false },
  { id: 735, section: "X", feature: "\"Ekran görüntüsü al\"", impl: "DONE", proof: "PA", batch: "B27", owner: false },
  { id: 736, section: "X", feature: "\"Dosyayı gönder\"", impl: "DONE", proof: "PA", batch: "B26", owner: false },
  { id: 737, section: "X", feature: "\"Bunu yazdır\"", impl: "DONE", proof: "PA", batch: "B26", owner: false },
  { id: 738, section: "X", feature: "\"Otomatik güncellemeleri kapat\"", impl: "DONE", proof: "PA", batch: "B26", owner: false },
  { id: 739, section: "X", feature: "Wrong-route negatives", impl: "DONE", proof: "PA", batch: "B26", owner: false },
  { id: 740, section: "X", feature: "Semantic model router", impl: "DONE", proof: "PA", batch: "B51", owner: false },
  { id: 741, section: "X", feature: "Deterministic safety router", impl: "DONE", proof: "PA", batch: "B26", owner: false },
  { id: 742, section: "X", feature: "Tool registry-driven routing", impl: "DONE", proof: "PA", batch: "B51", owner: false },
  { id: 743, section: "X", feature: "Intent confidence", impl: "DONE", proof: "PA", batch: "B51", owner: false },
  { id: 744, section: "X", feature: "Ambiguity clarification", impl: "DONE", proof: "PA", batch: "B51", owner: false },
  { id: 745, section: "X", feature: "Reference resolution", impl: "DONE", proof: "PA", batch: "B51", owner: false },
  { id: 746, section: "X", feature: "Turkish paraphrases", impl: "DONE", proof: "PA", batch: "B51", owner: false },
  { id: 747, section: "X", feature: "ASR-noise variants", impl: "DONE", proof: "PA", batch: "B51", owner: false },
  { id: 748, section: "X", feature: "Routing corpus expansion", impl: "DONE", proof: "PA", batch: "B51", owner: false },
  { id: 749, section: "X", feature: "Route telemetry", impl: "DONE", proof: "PA", batch: "B26", owner: false },
  { id: 750, section: "X", feature: "Misroute auto-detection", impl: "DONE", proof: "PA", batch: "B26", owner: false },
];
