"""On-device Turkish STT for MEASUREMENT: sherpa-onnx + a streaming Zipformer.

local-tr-stt-measure. The owner approved MEASURING it only (2026-10-04,
team/proposals/2026-10-04-cihazda-turkce-tanima.md): it is a row of ``stt_compare`` and
nothing else - the companion, the wake engine and the realtime path do not use it.
Wiring it into the companion is a separate decision.

* ``sherpa-onnx`` (Apache-2.0) is an OPTIONAL, hand-installed package, like faster-whisper: it is
  not in pyproject/uv.lock. Absent, the provider is inert and raises OPTIONAL_DEPENDENCY_MISSING.
* The model (``duxx/turkish-stt-zipformer``, CC BY-NC 4.0) is never in the repository. It lives
  in ``%LOCALAPPDATA%\\PagentOS\\models\\<MODEL_DIR_NAME>`` (or ``$PAGENTOS_SHERPA_MODEL_DIR``) and
  is pinned here: one commit, four files, a sha256 each. A missing file or a hash that differs
  means the model is NOT loaded - an ONNX graph is code, and the hash is the one guard against
  a damaged or substituted one.
* ``available()`` / ``status()`` read and hash the files but never build the recogniser.
* :func:`download_model` is the only network path: the pinned commit's URLs, each file to a
  ``.part`` beside its place, verified, then moved in. Called by hand, never by a test or a run.
"""

from __future__ import annotations

import hashlib
import importlib.util
import io
import os
import time
import wave
from collections.abc import Callable
from dataclasses import dataclass
from pathlib import Path
from typing import Any, BinaryIO

from app.voice.errors import VoiceError, VoiceErrorClass
from app.voice.providers import ProviderCapabilities, STTResult

MODEL_REPO = "duxx/turkish-stt-zipformer"
#: "Remove remaining generated bytecode", 2026-08-04T14:26:58Z (read 2026-10-04 from the HF API).
MODEL_COMMIT = "cebec199e0a9a1bdcd195b9124922b4a33e98bc8"
MODEL_DIR_NAME = "duxx-turkish-stt-zipformer-cebec199-int8"
MODEL_DIR_ENV = "PAGENTOS_SHERPA_MODEL_DIR"

ENCODER = "encoder-epoch-1-avg-1-chunk-32-left-128.int8.onnx"
DECODER = "decoder-epoch-1-avg-1-chunk-32-left-128.int8.onnx"
JOINER = "joiner-epoch-1-avg-1-chunk-32-left-128.int8.onnx"
TOKENS = "tokens.txt"
#: file -> sha256 of its content at ``MODEL_COMMIT`` (26 599 220 + 540 688 + 259 417 + 5 182 bytes).
MODEL_FILES: dict[str, str] = {
    ENCODER: "f5a4b439cf0dd11d01774a97fd580c20ad944756c7e44f539cb6a46165013432",
    DECODER: "28f4caee9c57dc22afc0967b7e81994b85c0b67f9980f1df0bb5648a7554b18b",
    JOINER: "c1f4ebed5cbbed2fceefabca8c2657f157bcf2deead3ad067c8b2dc1d2c3bfb1",
    TOKENS: "1885ade359d5939dde820f0f0a1b31f43dad6e5bf8362ad66983fb78d24d65b6",
}

#: ``ModelStatus.reason`` - also the ``stt_compare`` row reasons.
REASON_NOT_INSTALLED = "not installed"
REASON_MODEL_MISSING = "model missing"
REASON_MODEL_HASH = "model hash mismatch"

SAMPLE_RATE = 16_000
#: 0.5 s blocks in, then 1 s of silence: without the tail the last word is lost (the
#: model author's own transcribe.py does the same).
_CHUNK_S = 0.5
_TAIL_S = 1.0
_HASH_BLOCK = 1 << 20


def model_url(name: str) -> str:
    return f"https://huggingface.co/{MODEL_REPO}/resolve/{MODEL_COMMIT}/{name}"


def model_dir() -> Path:
    override = os.environ.get(MODEL_DIR_ENV, "").strip()
    if override:
        return Path(override)
    base = os.environ.get("LOCALAPPDATA", "").strip() or str(Path.home() / ".local" / "share")
    return Path(base) / "PagentOS" / "models" / MODEL_DIR_NAME


def _sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for block in iter(lambda: handle.read(_HASH_BLOCK), b""):
            digest.update(block)
    return digest.hexdigest()


@dataclass(frozen=True, slots=True)
class ModelStatus:
    ok: bool
    #: ``""`` when ok, else one of the ``REASON_*``.
    reason: str
    #: The Turkish sentence the owner reads.
    detail_tr: str


#: (path, size, mtime_ns) -> sha256: a 27 MB file is hashed once per change, not per listing.
_HASH_CACHE: dict[tuple[str, int, int], str] = {}


def _cached_sha256(path: Path) -> str:
    stat = path.stat()
    key = (str(path), stat.st_size, stat.st_mtime_ns)
    if key not in _HASH_CACHE:
        _HASH_CACHE[key] = _sha256(path)
    return _HASH_CACHE[key]


class SherpaOnnxSTTProvider:
    """Local, streaming, Turkish-only STT (measurement row of ``stt_compare``)."""

    name = "sherpa-onnx"

    def __init__(self, *, folder: Path | None = None, num_threads: int = 4) -> None:
        self._folder = folder
        self._num_threads = num_threads
        self._recognizer: Any = None

    def capabilities(self) -> ProviderCapabilities:
        return ProviderCapabilities(
            name=self.name,
            kind="stt",
            languages=("tr-TR",),
            streaming=True,
            long_form_stability="n/a",
            pronunciation_dict=False,
            voice_selection=False,
            speed_control=False,
            cost_metadata={"unit": "local_compute", "usd": 0.0, "billing": "local/offline"},
            output_formats=("text",),
            latency_class="streaming",
            requires_api_key=False,
        )

    def folder(self) -> Path:
        return self._folder if self._folder is not None else model_dir()

    def status(self) -> ModelStatus:
        """Package, then every file, then every hash - in that order, so the first thing
        missing is the one named. Reads the files; never builds the recogniser."""
        try:
            installed = importlib.util.find_spec("sherpa_onnx") is not None
        except (ImportError, ValueError):  # pragma: no cover - a broken installation
            installed = False
        if not installed:
            return ModelStatus(
                False,
                REASON_NOT_INSTALLED,
                "sherpa-onnx kurulu değil "
                "(isteğe bağlı paket: uv pip install sherpa-onnx==1.13.8).",
            )
        folder = self.folder()
        missing = [name for name in MODEL_FILES if not (folder / name).is_file()]
        if missing:
            return ModelStatus(
                False,
                REASON_MODEL_MISSING,
                f"Türkçe model eksik: {', '.join(missing)} ({folder} içinde yok).",
            )
        for name, expected in MODEL_FILES.items():
            if _cached_sha256(folder / name) != expected:
                return ModelStatus(
                    False,
                    REASON_MODEL_HASH,
                    f"Model dosyası {name} sabitlenen hash ile tutmuyor; yüklenmedi.",
                )
        return ModelStatus(True, "", "")

    def available(self) -> bool:
        return self.status().ok

    def _load(self) -> Any:
        if self._recognizer is not None:
            return self._recognizer
        status = self.status()
        if not status.ok:
            raise VoiceError(
                VoiceErrorClass.OPTIONAL_DEPENDENCY_MISSING,
                status.detail_tr,
                provider=self.name,
                details={"reason": status.reason},
            )
        try:
            import sherpa_onnx  # type: ignore[import-not-found]
        except ImportError as exc:  # found by find_spec, broken on import
            raise VoiceError(
                VoiceErrorClass.OPTIONAL_DEPENDENCY_MISSING,
                "sherpa-onnx yüklenemedi (isteğe bağlı yerel tanıyıcı).",
                provider=self.name,
            ) from exc
        folder = self.folder()
        # the author's settings, the ones the published dev-set WER was measured with
        self._recognizer = sherpa_onnx.OnlineRecognizer.from_transducer(
            tokens=str(folder / TOKENS),
            encoder=str(folder / ENCODER),
            decoder=str(folder / DECODER),
            joiner=str(folder / JOINER),
            num_threads=self._num_threads,
            sample_rate=SAMPLE_RATE,
            feature_dim=80,
            decoding_method="modified_beam_search",
            max_active_paths=12,
            blank_penalty=0.0,
            provider="cpu",
            enable_endpoint_detection=False,
        )
        return self._recognizer

    @staticmethod
    def _samples(audio: bytes) -> list[float]:
        bad = VoiceError(
            VoiceErrorClass.VALIDATION_ERROR,
            "Yerel tanıyıcı yalnız WAV, PCM 16 bit, mono, 16 kHz okur.",
            provider="sherpa-onnx",
        )
        try:
            with wave.open(io.BytesIO(audio), "rb") as wav:
                if (wav.getframerate(), wav.getnchannels(), wav.getsampwidth()) != (
                    SAMPLE_RATE,
                    1,
                    2,
                ):
                    raise bad
                frames = wav.readframes(wav.getnframes())
        except (wave.Error, EOFError) as exc:
            raise bad from exc
        count = len(frames) // 2
        values = memoryview(frames[: count * 2]).cast("h")
        return [value / 32768.0 for value in values]

    def transcribe(self, audio: bytes, *, language: str = "tr-TR") -> STTResult:
        samples = self._samples(audio)
        recognizer = self._load()  # raises before anything is read into a model
        started = time.perf_counter()
        stream = recognizer.create_stream()
        chunk = int(_CHUNK_S * SAMPLE_RATE)
        for begin in range(0, len(samples), chunk):
            stream.accept_waveform(SAMPLE_RATE, samples[begin : begin + chunk])
            while recognizer.is_ready(stream):
                recognizer.decode_stream(stream)
        stream.accept_waveform(SAMPLE_RATE, [0.0] * int(_TAIL_S * SAMPLE_RATE))
        stream.input_finished()
        while recognizer.is_ready(stream):
            recognizer.decode_stream(stream)
        result = recognizer.get_result(stream)
        text = result if isinstance(result, str) else str(getattr(result, "text", ""))
        return STTResult(
            text=text.strip(),
            confidence=1.0,
            word_timings=(),
            latency_ms=round((time.perf_counter() - started) * 1000, 2),
            provider=self.name,
            language=language,
        )


def _open_url(url: str, timeout: float) -> BinaryIO:  # pragma: no cover - the network
    from urllib.request import urlopen

    return urlopen(url, timeout=timeout)  # type: ignore[no-any-return]  # noqa: S310 - pinned https URL


def download_model(
    folder: Path | None = None,
    *,
    opener: Callable[[str, float], Any] = _open_url,
    timeout_s: float = 120.0,
) -> Path:
    """Fetch the four pinned files into ``folder`` (default :func:`model_dir`). Each goes to
    ``<name>.part``, is hashed, and only then replaces ``<name>``; a hash that differs
    deletes the ``.part`` and raises. A file already present and correct is not fetched."""
    target = folder if folder is not None else model_dir()
    target.mkdir(parents=True, exist_ok=True)
    for name, expected in MODEL_FILES.items():
        final = target / name
        if final.is_file() and _sha256(final) == expected:
            continue
        part = target / f"{name}.part"
        digest = hashlib.sha256()
        try:
            with opener(model_url(name), timeout_s) as response, part.open("wb") as out:
                for block in iter(lambda: response.read(_HASH_BLOCK), b""):
                    digest.update(block)
                    out.write(block)
            if digest.hexdigest() != expected:
                raise VoiceError(
                    VoiceErrorClass.VALIDATION_ERROR,
                    f"İndirilen {name} sabitlenen hash ile tutmuyor; yerine konmadı.",
                    provider="sherpa-onnx",
                )
            os.replace(part, final)
        finally:
            part.unlink(missing_ok=True)
    return target


__all__ = [
    "MODEL_COMMIT",
    "MODEL_DIR_ENV",
    "MODEL_DIR_NAME",
    "MODEL_FILES",
    "REASON_MODEL_HASH",
    "REASON_MODEL_MISSING",
    "REASON_NOT_INSTALLED",
    "ModelStatus",
    "SherpaOnnxSTTProvider",
    "download_model",
    "model_dir",
    "model_url",
]
